-- ============================================================
-- ATLAS Ledger ("Provenance") — Phase 0: the spine
--
-- An append-only, hash-chained decision record. The invariant:
-- the Ledger may never flatter you. Every mechanism here exists
-- to keep the record tamper-evident and forward-only.
--
--   orders            — persisted execution audit trail (was Alpaca-only)
--   decisions         — one row per decision (executed OR passed); append-only
--   decision_outcomes — what happened, at multiple horizons; append-only
--   vw_ledger_integrity — recomputes the hash chain → OK / broken
--
-- Defaults locked with Hlobo: "correct" = beat benchmark; benchmark = SPY;
-- conviction→prob linear (p = c/100); horizons 30/60/90/to-date;
-- hash-chain ON in v1.
-- ============================================================

create extension if not exists pgcrypto;

-- ── orders: persisted execution trail ───────────────────────
-- /api/trading writes here on every submit (idempotent on client_order_id).
-- The broker remains ground truth; this is the local audit copy the Ledger
-- and reconciliation hang off.
create table if not exists orders (
  id               uuid primary key default gen_random_uuid(),
  client_order_id  text unique,
  alpaca_order_id  text,
  symbol           text not null,
  side             text,            -- buy | sell
  type             text,            -- market | limit | stop | stop_limit
  qty              numeric,
  notional         numeric,
  status           text,            -- submitting|confirming|filled|partially_filled|rejected|unknown|accepted|new|canceled
  filled_qty       numeric,
  filled_avg_price numeric,
  reject_reason    text,
  submitted_at     timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  raw              jsonb
);

alter table orders enable row level security;
do $$ begin
  create policy orders_anon_read on orders for select using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy orders_service_all on orders for all using (auth.role() = 'service_role');
exception when duplicate_object then null; end $$;

-- ── decisions: the canonical ledger (append-only) ───────────
create table if not exists decisions (
  id              uuid primary key default gen_random_uuid(),
  seq             bigint generated by default as identity,  -- monotonic chain order (UUIDs aren't ordered)
  created_at      timestamptz not null default now(),   -- server-stamped, never client-set
  decided_at      timestamptz not null default now(),
  symbol          text not null,
  entity_type     text default 'holding',     -- holding | sector | theme | region
  decision_type   text not null,              -- executed | passed | considered
  intent          text,                        -- add | trim | exit | hold | avoid
  order_id        uuid references orders(id),  -- set when executed; null when passed
  conviction      int,                         -- 0–100 stated/Nexus conviction at decision time
  signal_snapshot jsonb,                        -- full Nexus row at decision time
  rationale       text,
  benchmark       text default 'SPY',
  content_hash    text,                         -- sha256 of canonical fields (set by trigger)
  prev_hash       text,                         -- hash-chain link to the previous decision (set by trigger)
  supersedes_id   uuid references decisions(id) -- corrections append + point back; never edit
);

create index if not exists idx_decisions_symbol  on decisions(symbol);
create index if not exists idx_decisions_created  on decisions(created_at);
create index if not exists idx_decisions_type     on decisions(decision_type);
create index if not exists idx_decisions_seq      on decisions(seq);

-- ── decision_outcomes: multi-horizon results (append-only) ──
create table if not exists decision_outcomes (
  id               uuid primary key default gen_random_uuid(),
  decision_id      uuid not null references decisions(id),
  horizon_days     int not null,                -- 30 | 60 | 90 | 0 (0 = to-date rolling)
  snapshot_at      timestamptz not null default now(),
  entity_return    numeric,
  benchmark_return numeric,
  alpha            numeric,                      -- entity_return - benchmark_return
  correct          boolean,                      -- did the implied call beat the benchmark?
  unique(decision_id, horizon_days)
);

-- ── hash-chain trigger (tamper-evidence) ────────────────────
-- Server-stamps created_at, links prev_hash to the latest row, and computes
-- content_hash over the canonical fields. An advisory lock serialises appends
-- so the chain stays single-threaded and well-defined.
create or replace function decisions_hash_chain() returns trigger as $$
declare
  last_hash text;
  canon     text;
begin
  new.created_at := clock_timestamp();           -- distinct per-row time; never trust a client timestamp
  perform pg_advisory_xact_lock(hashtext('atlas_decisions_chain'));
  select content_hash into last_hash from decisions order by seq desc limit 1;
  new.prev_hash := coalesce(last_hash, '');
  canon :=
    coalesce(new.symbol,'')              || '|' ||
    coalesce(new.decided_at::text,'')    || '|' ||
    coalesce(new.decision_type,'')       || '|' ||
    coalesce(new.intent,'')              || '|' ||
    coalesce(new.conviction::text,'')    || '|' ||
    coalesce(new.signal_snapshot::text,'') || '|' ||
    coalesce(new.rationale,'')           || '|' ||
    coalesce(new.prev_hash,'');
  new.content_hash := encode(digest(canon, 'sha256'), 'hex');
  return new;
end $$ language plpgsql;

drop trigger if exists trg_decisions_hash on decisions;
create trigger trg_decisions_hash before insert on decisions
  for each row execute function decisions_hash_chain();

-- ── append-only enforcement ─────────────────────────────────
create or replace function deny_mutation() returns trigger as $$
begin raise exception '% is append-only — corrections append a new row', tg_table_name; end $$ language plpgsql;

drop trigger if exists no_mutate_decisions on decisions;
create trigger no_mutate_decisions before update or delete on decisions
  for each row execute function deny_mutation();

drop trigger if exists no_mutate_outcomes on decision_outcomes;
create trigger no_mutate_outcomes before update or delete on decision_outcomes
  for each row execute function deny_mutation();

-- RLS: anyone may read + append; nobody may mutate (trigger + no update/delete policy)
alter table decisions enable row level security;
do $$ begin
  create policy decisions_anon_read on decisions for select using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy decisions_anon_insert on decisions for insert with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy decisions_service_all on decisions for all using (auth.role() = 'service_role');
exception when duplicate_object then null; end $$;

alter table decision_outcomes enable row level security;
do $$ begin
  create policy outcomes_anon_read on decision_outcomes for select using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy outcomes_service_all on decision_outcomes for all using (auth.role() = 'service_role');
exception when duplicate_object then null; end $$;

-- ── integrity verification ──────────────────────────────────
-- Recomputes the chain: every row's prev_hash must equal the previous row's
-- content_hash, AND its content_hash must equal a fresh hash of its fields.
-- The UI's "hash-chain verified" badge reads chain_ok from here.
create or replace view vw_ledger_integrity as
with ordered as (
  select
    id, created_at, content_hash, prev_hash,
    lag(content_hash) over (order by seq) as expected_prev,
    encode(digest(
      coalesce(symbol,'')              || '|' ||
      coalesce(decided_at::text,'')    || '|' ||
      coalesce(decision_type,'')       || '|' ||
      coalesce(intent,'')              || '|' ||
      coalesce(conviction::text,'')    || '|' ||
      coalesce(signal_snapshot::text,'') || '|' ||
      coalesce(rationale,'')           || '|' ||
      coalesce(prev_hash,'')
    , 'sha256'), 'hex') as recomputed_hash
  from decisions
)
select
  count(*)                                                                              as total,
  count(*) filter (where prev_hash is distinct from coalesce(expected_prev,''))         as broken_links,
  count(*) filter (where content_hash is distinct from recomputed_hash)                 as tampered_rows,
  (
    count(*) filter (where prev_hash is distinct from coalesce(expected_prev,'')) = 0 and
    count(*) filter (where content_hash is distinct from recomputed_hash) = 0
  )                                                                                      as chain_ok,
  max(created_at)                                                                        as last_decision_at
from ordered;
