-- MP-5: the verdict engine runs per account.
--
-- MP-2 gated position verdicts, segment verdicts and everything under them to
-- the default account, because the six materialised views the engine rests on
-- are refreshed by pg_cron with no request header and so only ever held the
-- default book. Joined on asset_id to another account's rows they would have
-- attached Primary's verdicts to any name both accounts hold.
--
-- The fix is the MP-4d shape applied to a chain rather than one object:
--
--   <name>__acct     table, (portfolio_id, <the matview's columns>)
--   <name>           view over it for atlas_active_portfolio() -- the name every
--                    consumer (views, functions, the browser) already reads
--   <name>__compute  the matview's own definition, unchanged, as a view
--
-- A recompute sets the header to one account and runs each __compute in
-- dependency order; because every upstream name is itself per-account, each
-- stage reads the same account's upstream. Nothing downstream changes text
-- except the ten MP-2 guards on these sources, which are dropped: the sources
-- now answer for the active account instead of withholding it.
--
-- position_verdicts and segment_verdicts gain portfolio_id (existing rows are
-- the default account's, which is what the column default backfills), and the
-- writers run once per account under that account's header.
--
-- Sections 1-6 are generated from the live definitions (gen5b.py); 7-11 are
-- hand-written. book_factor_betas, book_regime_cvar and var_backtest_runs stay
-- default-only: they regress an account's own daily returns and Atlas Secondary
-- has one. They are recomputable later from portfolio_equity_curve, which is
-- already recorded per account, so nothing is lost by waiting.

-- generated by gen5b.py from the live definitions; see header in the migration file

-- 1. retire the matviews (dependents follow the OID until repointed below)
alter materialized view public.mv_book_daily_weights rename to mv_book_daily_weights__retired;
alter materialized view public.mv_book_ex_index rename to mv_book_ex_index__retired;
alter materialized view public.mv_position_returns rename to mv_position_returns__retired;
alter materialized view public.mv_position_tier2 rename to mv_position_tier2__retired;
alter materialized view public.mv_position_tier1 rename to mv_position_tier1__retired;
alter materialized view public.mv_segment_ex_index rename to mv_segment_ex_index__retired;

-- 2. per-account storage, seeded with the rows the matview holds now (the default account's)
create table public.mv_book_daily_weights__acct as
  select public.atlas_default_portfolio() as portfolio_id, r.* from public.mv_book_daily_weights__retired r;
alter table public.mv_book_daily_weights__acct alter column portfolio_id set not null,
  add constraint mv_book_daily_weights__acct_portfolio_fk foreign key (portfolio_id) references public.portfolios(id) on delete cascade;
CREATE INDEX mv_book_daily_weights_asset_idx__acct ON public.mv_book_daily_weights__acct USING btree (portfolio_id, asset_id, price_date);
CREATE UNIQUE INDEX mv_book_daily_weights_uniq__acct ON public.mv_book_daily_weights__acct USING btree (portfolio_id, price_date, asset_id);
alter table public.mv_book_daily_weights__acct enable row level security;
revoke all on public.mv_book_daily_weights__acct from public, anon, authenticated;
create table public.mv_book_ex_index__acct as
  select public.atlas_default_portfolio() as portfolio_id, r.* from public.mv_book_ex_index__retired r;
alter table public.mv_book_ex_index__acct alter column portfolio_id set not null,
  add constraint mv_book_ex_index__acct_portfolio_fk foreign key (portfolio_id) references public.portfolios(id) on delete cascade;
CREATE UNIQUE INDEX mv_book_ex_index_uniq__acct ON public.mv_book_ex_index__acct USING btree (portfolio_id, asset_id, price_date);
alter table public.mv_book_ex_index__acct enable row level security;
revoke all on public.mv_book_ex_index__acct from public, anon, authenticated;
create table public.mv_position_returns__acct as
  select public.atlas_default_portfolio() as portfolio_id, r.* from public.mv_position_returns__retired r;
alter table public.mv_position_returns__acct alter column portfolio_id set not null,
  add constraint mv_position_returns__acct_portfolio_fk foreign key (portfolio_id) references public.portfolios(id) on delete cascade;
CREATE UNIQUE INDEX mv_position_returns_asset_uniq__acct ON public.mv_position_returns__acct USING btree (portfolio_id, asset_id);
CREATE INDEX mv_position_returns_symbol_idx__acct ON public.mv_position_returns__acct USING btree (portfolio_id, symbol);
alter table public.mv_position_returns__acct enable row level security;
revoke all on public.mv_position_returns__acct from public, anon, authenticated;
create table public.mv_position_tier2__acct as
  select public.atlas_default_portfolio() as portfolio_id, r.* from public.mv_position_tier2__retired r;
alter table public.mv_position_tier2__acct alter column portfolio_id set not null,
  add constraint mv_position_tier2__acct_portfolio_fk foreign key (portfolio_id) references public.portfolios(id) on delete cascade;
CREATE UNIQUE INDEX mv_position_tier2_asset_uniq__acct ON public.mv_position_tier2__acct USING btree (portfolio_id, asset_id);
CREATE INDEX mv_position_tier2_symbol_idx__acct ON public.mv_position_tier2__acct USING btree (portfolio_id, symbol);
alter table public.mv_position_tier2__acct enable row level security;
revoke all on public.mv_position_tier2__acct from public, anon, authenticated;
create table public.mv_position_tier1__acct as
  select public.atlas_default_portfolio() as portfolio_id, r.* from public.mv_position_tier1__retired r;
alter table public.mv_position_tier1__acct alter column portfolio_id set not null,
  add constraint mv_position_tier1__acct_portfolio_fk foreign key (portfolio_id) references public.portfolios(id) on delete cascade;
CREATE UNIQUE INDEX mv_position_tier1_asset_uniq__acct ON public.mv_position_tier1__acct USING btree (portfolio_id, asset_id);
CREATE INDEX mv_position_tier1_symbol_idx__acct ON public.mv_position_tier1__acct USING btree (portfolio_id, symbol);
alter table public.mv_position_tier1__acct enable row level security;
revoke all on public.mv_position_tier1__acct from public, anon, authenticated;
create table public.mv_segment_ex_index__acct as
  select public.atlas_default_portfolio() as portfolio_id, r.* from public.mv_segment_ex_index__retired r;
alter table public.mv_segment_ex_index__acct alter column portfolio_id set not null,
  add constraint mv_segment_ex_index__acct_portfolio_fk foreign key (portfolio_id) references public.portfolios(id) on delete cascade;
CREATE UNIQUE INDEX mv_segment_ex_index_pk__acct ON public.mv_segment_ex_index__acct USING btree (portfolio_id, "grouping", segment_id, price_date);
alter table public.mv_segment_ex_index__acct enable row level security;
revoke all on public.mv_segment_ex_index__acct from public, anon, authenticated;

-- 3. the names every consumer already reads now answer for the active account
create view public.mv_book_daily_weights as
 select price_date,
       asset_id,
       symbol,
       w,
       r,
       wr
   from public.mv_book_daily_weights__acct
  where portfolio_id = (select public.atlas_active_portfolio());
revoke all on public.mv_book_daily_weights from public, anon, authenticated;
grant select on public.mv_book_daily_weights to anon, authenticated, service_role;
create view public.mv_book_ex_index as
 select asset_id,
       symbol,
       price_date,
       r_ex,
       asset_priced_that_day,
       surviving_weight,
       ex_index
   from public.mv_book_ex_index__acct
  where portfolio_id = (select public.atlas_active_portfolio());
revoke all on public.mv_book_ex_index from public, anon, authenticated;
grant select on public.mv_book_ex_index to anon, authenticated, service_role;
create view public.mv_position_returns as
 select asset_id,
       symbol,
       position_state,
       engine_status,
       engine_reason,
       first_flow_date,
       last_trade_date,
       schedule_end_date,
       days_held,
       n_buys,
       n_sells,
       net_qty,
       broker_qty,
       capital_deployed_usd,
       proceeds_usd,
       terminal_value_usd,
       net_pnl_usd,
       simple_return_pct,
       position_mwr_period_pct,
       position_mwr_close_basis_pct,
       execution_effect_pp,
       position_mwr_pct,
       mwr_annualisable,
       position_twr_pct,
       window_open_price,
       window_close_price,
       mark_days_old,
       mark_price_date,
       ledger_complete,
       broker_reconciles,
       flow_dates,
       flow_amounts,
       computed_at
   from public.mv_position_returns__acct
  where portfolio_id = (select public.atlas_active_portfolio());
revoke all on public.mv_position_returns from public, anon, authenticated;
grant select on public.mv_position_returns to anon, authenticated, service_role;
create view public.mv_position_tier2 as
 select asset_id,
       symbol,
       position_state,
       engine_status,
       engine_reason,
       position_mwr_period_pct,
       cf_book_return_pct,
       cf_book_capital_deployed_usd,
       cf_book_net_pnl_usd,
       cf_book_status,
       cf_book_reason,
       excess_vs_book_pct,
       best_correlate_rho,
       best_correlate_symbol,
       absent_from_matrix,
       correlation_as_of,
       computed_at
   from public.mv_position_tier2__acct
  where portfolio_id = (select public.atlas_active_portfolio());
revoke all on public.mv_position_tier2 from public, anon, authenticated;
grant select on public.mv_position_tier2 to anon, authenticated, service_role;
create view public.mv_position_tier1 as
 select asset_id,
       symbol,
       cluster_size_nominal,
       cluster_size,
       avg_intra_rho,
       cluster_eligible,
       cluster_threshold_rho,
       cf_median_return_pct,
       cf_best_return_pct,
       cf_best_symbol,
       cf_basket_return_pct,
       cluster_dispersion,
       selection_effect_pct,
       regret_vs_best_pct,
       selection_effect_vol_adj,
       correlation_as_of,
       rank_in_cluster,
       cluster_members,
       computed_at
   from public.mv_position_tier1__acct
  where portfolio_id = (select public.atlas_active_portfolio());
revoke all on public.mv_position_tier1 from public, anon, authenticated;
grant select on public.mv_position_tier1 to anon, authenticated, service_role;
create view public.mv_segment_ex_index as
 select "grouping",
       segment_id,
       price_date,
       r_ex,
       segment_priced_that_day,
       surviving_weight,
       ex_index
   from public.mv_segment_ex_index__acct
  where portfolio_id = (select public.atlas_active_portfolio());
revoke all on public.mv_segment_ex_index from public, anon, authenticated;
grant select on public.mv_segment_ex_index to anon, authenticated, service_role;

-- 4. the computations the matviews used to hold, as views over the per-account names
create view public.mv_book_daily_weights__compute as
 WITH held AS (
         SELECT DISTINCT vw_position_nav_daily.asset_id
           FROM vw_position_nav_daily
        ), px AS (
         SELECT ph.asset_id,
            ph.price_date,
            ph.close,
            lag(ph.close) OVER (PARTITION BY ph.asset_id ORDER BY ph.price_date) AS prev_close
           FROM price_history ph
             JOIN held h ON h.asset_id = ph.asset_id
          WHERE ph."interval" = '1d'::text AND ph.price_date >= (( SELECT min(vw_position_nav_daily.price_date) - 10
                   FROM vw_position_nav_daily))
        ), ret AS (
         SELECT px.asset_id,
            px.price_date,
            px.close / px.prev_close - 1::numeric AS r
           FROM px
          WHERE px.prev_close > 0::numeric
        ), wt AS (
         SELECT n.asset_id,
            n.symbol,
            n.price_date,
            n.position_value / NULLIF(sum(n.position_value) OVER (PARTITION BY n.price_date), 0::numeric) AS w
           FROM vw_position_nav_daily n
          WHERE n.position_value IS NOT NULL
        )
 SELECT w.price_date,
    w.asset_id,
    w.symbol,
    w.w,
    r.r,
    w.w * r.r AS wr
   FROM wt w
     JOIN ret r ON r.asset_id = w.asset_id AND r.price_date = w.price_date;
revoke all on public.mv_book_daily_weights__compute from public, anon, authenticated;
create view public.mv_book_ex_index__compute as
 WITH day AS (
         SELECT mv_book_daily_weights.price_date,
            sum(mv_book_daily_weights.w) AS f,
            sum(mv_book_daily_weights.wr) AS s
           FROM mv_book_daily_weights
          GROUP BY mv_book_daily_weights.price_date
        ), universe AS (
         SELECT DISTINCT mv_book_daily_weights.asset_id,
            mv_book_daily_weights.symbol
           FROM mv_book_daily_weights
        ), grid AS (
         SELECT u.asset_id,
            u.symbol,
            d.price_date,
            d.f,
            d.s,
            COALESCE(m.w, 0::numeric) AS w_i,
            COALESCE(m.wr, 0::numeric) AS wr_i,
            m.asset_id IS NOT NULL AS present
           FROM universe u
             CROSS JOIN day d
             LEFT JOIN mv_book_daily_weights m ON m.asset_id = u.asset_id AND m.price_date = d.price_date
        ), ex AS (
         SELECT g.asset_id,
            g.symbol,
            g.price_date,
            g.f,
            g.s,
            g.w_i,
            g.wr_i,
            g.present,
                CASE
                    WHEN (g.f - g.w_i) < 0.02 THEN NULL::numeric
                    ELSE (g.s - g.wr_i) / (g.f - g.w_i)
                END AS r_ex
           FROM grid g
        )
 SELECT asset_id,
    symbol,
    price_date,
    r_ex,
    present AS asset_priced_that_day,
    f - w_i AS surviving_weight,
    exp(sum(ln(1::numeric + r_ex)) OVER (PARTITION BY asset_id ORDER BY price_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)) AS ex_index
   FROM ex
  WHERE r_ex IS NOT NULL AND r_ex > '-1'::integer::numeric;
revoke all on public.mv_book_ex_index__compute from public, anon, authenticated;
create view public.mv_position_returns__compute as
 SELECT asset_id,
    symbol,
    position_state,
    engine_status,
    engine_reason,
    first_flow_date,
    last_trade_date,
    schedule_end_date,
    days_held,
    n_buys,
    n_sells,
    net_qty,
    broker_qty,
    capital_deployed_usd,
    proceeds_usd,
    terminal_value_usd,
    net_pnl_usd,
    simple_return_pct,
    position_mwr_period_pct,
    position_mwr_close_basis_pct,
    execution_effect_pp,
    position_mwr_pct,
    mwr_annualisable,
    position_twr_pct,
    window_open_price,
    window_close_price,
    mark_days_old,
    mark_price_date,
    ledger_complete,
    broker_reconciles,
    flow_dates,
    flow_amounts,
    now() AS computed_at
   FROM vw_position_returns r;
revoke all on public.mv_position_returns__compute from public, anon, authenticated;
create view public.mv_position_tier2__compute as
 SELECT asset_id,
    symbol,
    position_state,
    engine_status,
    engine_reason,
    position_mwr_period_pct,
    cf_book_return_pct,
    cf_book_capital_deployed_usd,
    cf_book_net_pnl_usd,
    cf_book_status,
    cf_book_reason,
    excess_vs_book_pct,
    best_correlate_rho,
    best_correlate_symbol,
    absent_from_matrix,
    correlation_as_of,
    now() AS computed_at
   FROM vw_position_tier2 t;
revoke all on public.mv_position_tier2__compute from public, anon, authenticated;
create view public.mv_position_tier1__compute as
 SELECT asset_id,
    symbol,
    cluster_size_nominal,
    cluster_size,
    avg_intra_rho,
    cluster_eligible,
    cluster_threshold_rho,
    cf_median_return_pct,
    cf_best_return_pct,
    cf_best_symbol,
    cf_basket_return_pct,
    cluster_dispersion,
    selection_effect_pct,
    regret_vs_best_pct,
    selection_effect_vol_adj,
    correlation_as_of,
    rank_in_cluster,
    cluster_members,
    now() AS computed_at
   FROM vw_position_tier1 t;
revoke all on public.mv_position_tier1__compute from public, anon, authenticated;
create view public.mv_segment_ex_index__compute as
 WITH day AS (
         SELECT b.price_date,
            sum(b.w) AS f,
            sum(b.wr) AS s
           FROM mv_book_daily_weights b
          GROUP BY b.price_date
        ), segs AS (
         SELECT DISTINCT p."grouping",
            p.segment_id
           FROM vw_position_segments p
        ), seg_day AS (
         SELECT p."grouping",
            p.segment_id,
            b.price_date,
            sum(b.w) AS w_s,
            sum(b.wr) AS wr_s
           FROM mv_book_daily_weights b
             JOIN vw_position_segments p ON p.asset_id = b.asset_id
          GROUP BY p."grouping", p.segment_id, b.price_date
        ), grid AS (
         SELECT s."grouping",
            s.segment_id,
            d.price_date,
            d.f,
            d.s AS s_tot,
            COALESCE(sd.w_s, 0::numeric) AS w_s,
            COALESCE(sd.wr_s, 0::numeric) AS wr_s,
            sd.segment_id IS NOT NULL AS segment_priced_that_day
           FROM segs s
             CROSS JOIN day d
             LEFT JOIN seg_day sd ON sd."grouping" = s."grouping" AND sd.segment_id = s.segment_id AND sd.price_date = d.price_date
        ), ex AS (
         SELECT g."grouping",
            g.segment_id,
            g.price_date,
            g.f,
            g.s_tot,
            g.w_s,
            g.wr_s,
            g.segment_priced_that_day,
                CASE
                    WHEN (g.f - g.w_s) < 0.02 THEN NULL::numeric
                    ELSE (g.s_tot - g.wr_s) / (g.f - g.w_s)
                END AS r_ex
           FROM grid g
        )
 SELECT "grouping",
    segment_id,
    price_date,
    r_ex,
    segment_priced_that_day,
    f - w_s AS surviving_weight,
    exp(sum(ln(1::numeric + r_ex)) OVER (PARTITION BY "grouping", segment_id ORDER BY price_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)) AS ex_index
   FROM ex
  WHERE r_ex IS NOT NULL AND r_ex > (- 1::numeric);
revoke all on public.mv_segment_ex_index__compute from public, anon, authenticated;

-- 5. repoint dependents, dropping the single-book guards on these sources
-- vw_default_only_position_returns: 1 guard(s) removed
create or replace view public.vw_default_only_position_returns as
 SELECT asset_id,
    symbol,
    position_state,
    engine_status,
    engine_reason,
    first_flow_date,
    last_trade_date,
    schedule_end_date,
    days_held,
    n_buys,
    n_sells,
    net_qty,
    broker_qty,
    capital_deployed_usd,
    proceeds_usd,
    terminal_value_usd,
    net_pnl_usd,
    simple_return_pct,
    position_mwr_period_pct,
    position_mwr_close_basis_pct,
    execution_effect_pp,
    position_mwr_pct,
    mwr_annualisable,
    position_twr_pct,
    window_open_price,
    window_close_price,
    mark_days_old,
    mark_price_date,
    ledger_complete,
    broker_reconciles,
    flow_dates,
    flow_amounts,
    computed_at
   FROM mv_position_returns;
-- vw_position_cluster_members: 1 guard(s) removed
create or replace view public.vw_position_cluster_members as
 WITH latest_corr AS (
         SELECT max(universe_correlations.as_of_date) AS d
           FROM universe_correlations
        ), open_book AS (
         SELECT DISTINCT mv_position_returns.symbol,
            mv_position_returns.asset_id
           FROM ( SELECT mv_position_returns_1.asset_id,
                    mv_position_returns_1.symbol,
                    mv_position_returns_1.position_state,
                    mv_position_returns_1.engine_status,
                    mv_position_returns_1.engine_reason,
                    mv_position_returns_1.first_flow_date,
                    mv_position_returns_1.last_trade_date,
                    mv_position_returns_1.schedule_end_date,
                    mv_position_returns_1.days_held,
                    mv_position_returns_1.n_buys,
                    mv_position_returns_1.n_sells,
                    mv_position_returns_1.net_qty,
                    mv_position_returns_1.broker_qty,
                    mv_position_returns_1.capital_deployed_usd,
                    mv_position_returns_1.proceeds_usd,
                    mv_position_returns_1.terminal_value_usd,
                    mv_position_returns_1.net_pnl_usd,
                    mv_position_returns_1.simple_return_pct,
                    mv_position_returns_1.position_mwr_period_pct,
                    mv_position_returns_1.position_mwr_close_basis_pct,
                    mv_position_returns_1.execution_effect_pp,
                    mv_position_returns_1.position_mwr_pct,
                    mv_position_returns_1.mwr_annualisable,
                    mv_position_returns_1.position_twr_pct,
                    mv_position_returns_1.window_open_price,
                    mv_position_returns_1.window_close_price,
                    mv_position_returns_1.mark_days_old,
                    mv_position_returns_1.mark_price_date,
                    mv_position_returns_1.ledger_complete,
                    mv_position_returns_1.broker_reconciles,
                    mv_position_returns_1.flow_dates,
                    mv_position_returns_1.flow_amounts,
                    mv_position_returns_1.computed_at
                   FROM mv_position_returns mv_position_returns_1) mv_position_returns
          WHERE mv_position_returns.position_state = 'open'::text
        ), pairs AS (
         SELECT c.symbol_1 AS sym,
            c.symbol_2 AS other,
            c.correlation AS rho
           FROM universe_correlations c,
            latest_corr l
          WHERE c.as_of_date = l.d AND c.correlation >= 0.75
        UNION ALL
         SELECT c.symbol_2,
            c.symbol_1,
            c.correlation
           FROM universe_correlations c,
            latest_corr l
          WHERE c.as_of_date = l.d AND c.correlation >= 0.75
        )
 SELECT o.symbol,
    o.asset_id,
    p.other AS member_symbol,
    ca.asset_id AS member_asset_id,
    p.rho,
    ( SELECT latest_corr.d
           FROM latest_corr) AS correlation_as_of
   FROM open_book o
     JOIN pairs p ON p.sym = o.symbol AND p.other <> o.symbol
     JOIN vw_canonical_assets ca ON ca.symbol = p.other;
-- vw_position_frozen: 1 guard(s) removed
create or replace view public.vw_position_frozen as
 WITH val AS (
         SELECT max(c.flow_date) AS d
           FROM vw_position_cash_flows c
          WHERE c.flow_kind = 'mark'::text
        )
 SELECT r.asset_id,
    r.symbol,
    r.position_state,
    r.engine_status,
    r.position_mwr_period_pct,
    f.frozen_entry_date,
    f.frozen_qty,
    f.frozen_capital_usd,
    f.frozen_terminal_usd,
    f.frozen_mark_date,
    f.frozen_return_pct::numeric AS frozen_weight_return_pct,
    f.frozen_status,
    f.frozen_reason,
        CASE
            WHEN r.engine_status = 'measured'::text AND f.frozen_status = 'measured'::text AND r.position_mwr_period_pct IS NOT NULL AND f.frozen_return_pct IS NOT NULL THEN (r.position_mwr_period_pct::double precision - f.frozen_return_pct)::numeric
            ELSE NULL::numeric
        END AS trading_effect_pct
   FROM ( SELECT mv_position_returns.asset_id,
            mv_position_returns.symbol,
            mv_position_returns.position_state,
            mv_position_returns.engine_status,
            mv_position_returns.engine_reason,
            mv_position_returns.first_flow_date,
            mv_position_returns.last_trade_date,
            mv_position_returns.schedule_end_date,
            mv_position_returns.days_held,
            mv_position_returns.n_buys,
            mv_position_returns.n_sells,
            mv_position_returns.net_qty,
            mv_position_returns.broker_qty,
            mv_position_returns.capital_deployed_usd,
            mv_position_returns.proceeds_usd,
            mv_position_returns.terminal_value_usd,
            mv_position_returns.net_pnl_usd,
            mv_position_returns.simple_return_pct,
            mv_position_returns.position_mwr_period_pct,
            mv_position_returns.position_mwr_close_basis_pct,
            mv_position_returns.execution_effect_pp,
            mv_position_returns.position_mwr_pct,
            mv_position_returns.mwr_annualisable,
            mv_position_returns.position_twr_pct,
            mv_position_returns.window_open_price,
            mv_position_returns.window_close_price,
            mv_position_returns.mark_days_old,
            mv_position_returns.mark_price_date,
            mv_position_returns.ledger_complete,
            mv_position_returns.broker_reconciles,
            mv_position_returns.flow_dates,
            mv_position_returns.flow_amounts,
            mv_position_returns.computed_at
           FROM mv_position_returns) r
     CROSS JOIN LATERAL atlas_counterfactual_frozen(r.asset_id, ( SELECT val.d
           FROM val)) f(frozen_entry_date, frozen_qty, frozen_capital_usd, frozen_terminal_usd, frozen_mark_price, frozen_mark_date, frozen_return_pct, frozen_status, frozen_reason);
-- vw_position_segments: 1 guard(s) removed
create or replace view public.vw_position_segments as
 WITH clus AS (
         SELECT u.symbol,
            u.cluster_id
           FROM universe_clusters u
          WHERE u.as_of_date = (( SELECT max(u2.as_of_date) AS max
                   FROM universe_clusters u2))
        ), open_book AS (
         SELECT r.asset_id,
            r.symbol
           FROM ( SELECT mv_position_returns.asset_id,
                    mv_position_returns.symbol,
                    mv_position_returns.position_state,
                    mv_position_returns.engine_status,
                    mv_position_returns.engine_reason,
                    mv_position_returns.first_flow_date,
                    mv_position_returns.last_trade_date,
                    mv_position_returns.schedule_end_date,
                    mv_position_returns.days_held,
                    mv_position_returns.n_buys,
                    mv_position_returns.n_sells,
                    mv_position_returns.net_qty,
                    mv_position_returns.broker_qty,
                    mv_position_returns.capital_deployed_usd,
                    mv_position_returns.proceeds_usd,
                    mv_position_returns.terminal_value_usd,
                    mv_position_returns.net_pnl_usd,
                    mv_position_returns.simple_return_pct,
                    mv_position_returns.position_mwr_period_pct,
                    mv_position_returns.position_mwr_close_basis_pct,
                    mv_position_returns.execution_effect_pp,
                    mv_position_returns.position_mwr_pct,
                    mv_position_returns.mwr_annualisable,
                    mv_position_returns.position_twr_pct,
                    mv_position_returns.window_open_price,
                    mv_position_returns.window_close_price,
                    mv_position_returns.mark_days_old,
                    mv_position_returns.mark_price_date,
                    mv_position_returns.ledger_complete,
                    mv_position_returns.broker_reconciles,
                    mv_position_returns.flow_dates,
                    mv_position_returns.flow_amounts,
                    mv_position_returns.computed_at
                   FROM mv_position_returns) r
          WHERE r.position_state = 'open'::text
        ), base AS (
         SELECT o.asset_id,
            o.symbol,
            c.cluster_id,
            pt.theme
           FROM open_book o
             LEFT JOIN clus c ON c.symbol = o.symbol
             LEFT JOIN position_themes pt ON pt.symbol = o.symbol
        )
 SELECT b.asset_id,
    b.symbol,
    'bet'::text AS "grouping",
        CASE
            WHEN b.cluster_id IS NOT NULL THEN 'cluster:'::text || b.cluster_id::text
            WHEN b.theme IS NOT NULL THEN 'theme:'::text || b.theme
            ELSE 'unpaired'::text
        END AS segment_id,
        CASE
            WHEN b.cluster_id IS NOT NULL THEN 'cluster'::text
            WHEN b.theme IS NOT NULL THEN 'theme'::text
            ELSE 'unpaired'::text
        END AS segment_kind,
        CASE
            WHEN b.cluster_id IS NOT NULL THEN 'Cluster '::text || b.cluster_id::text
            WHEN b.theme IS NOT NULL THEN b.theme
            ELSE 'Unpaired'::text
        END AS segment_label,
    b.cluster_id,
    b.theme
   FROM base b
UNION ALL
 SELECT b.asset_id,
    b.symbol,
    'theme'::text AS "grouping",
        CASE
            WHEN b.theme IS NOT NULL THEN 'theme:'::text || b.theme
            ELSE 'unpaired'::text
        END AS segment_id,
        CASE
            WHEN b.theme IS NOT NULL THEN 'theme'::text
            ELSE 'unpaired'::text
        END AS segment_kind,
    COALESCE(b.theme, 'Unpaired'::text) AS segment_label,
    b.cluster_id,
    b.theme
   FROM base b;
-- vw_position_tier1: 2 guard(s) removed
create or replace view public.vw_position_tier1 as
 WITH cf AS (
         SELECT m.symbol,
            m.asset_id,
            m.member_symbol,
            m.rho,
            c.cf_mwr_period_pct,
            c.cf_status,
            own.position_mwr_period_pct AS own_return,
            own.engine_status AS own_status
           FROM vw_position_cluster_members m
             CROSS JOIN LATERAL atlas_counterfactual(m.asset_id, m.member_asset_id) c(peer_symbol, cf_capital_deployed_usd, cf_proceeds_usd, cf_terminal_value_usd, cf_net_pnl_usd, cf_mwr_period_pct, cf_status, cf_reason)
             LEFT JOIN ( SELECT mv_position_returns.asset_id,
                    mv_position_returns.symbol,
                    mv_position_returns.position_state,
                    mv_position_returns.engine_status,
                    mv_position_returns.engine_reason,
                    mv_position_returns.first_flow_date,
                    mv_position_returns.last_trade_date,
                    mv_position_returns.schedule_end_date,
                    mv_position_returns.days_held,
                    mv_position_returns.n_buys,
                    mv_position_returns.n_sells,
                    mv_position_returns.net_qty,
                    mv_position_returns.broker_qty,
                    mv_position_returns.capital_deployed_usd,
                    mv_position_returns.proceeds_usd,
                    mv_position_returns.terminal_value_usd,
                    mv_position_returns.net_pnl_usd,
                    mv_position_returns.simple_return_pct,
                    mv_position_returns.position_mwr_period_pct,
                    mv_position_returns.position_mwr_close_basis_pct,
                    mv_position_returns.execution_effect_pp,
                    mv_position_returns.position_mwr_pct,
                    mv_position_returns.mwr_annualisable,
                    mv_position_returns.position_twr_pct,
                    mv_position_returns.window_open_price,
                    mv_position_returns.window_close_price,
                    mv_position_returns.mark_days_old,
                    mv_position_returns.mark_price_date,
                    mv_position_returns.ledger_complete,
                    mv_position_returns.broker_reconciles,
                    mv_position_returns.flow_dates,
                    mv_position_returns.flow_amounts,
                    mv_position_returns.computed_at
                   FROM mv_position_returns) own ON own.asset_id = m.asset_id
        ), agg AS (
         SELECT cf.symbol,
            cf.asset_id,
            count(*) AS cluster_size_nominal,
            count(*) FILTER (WHERE cf.cf_mwr_period_pct IS NOT NULL) AS cluster_size,
            avg(cf.rho) FILTER (WHERE cf.cf_mwr_period_pct IS NOT NULL) AS avg_intra_rho,
            percentile_cont(0.5::double precision) WITHIN GROUP (ORDER BY cf.cf_mwr_period_pct) AS cf_median_return_pct,
            max(cf.cf_mwr_period_pct) AS cf_best_return_pct,
            stddev_samp(cf.cf_mwr_period_pct) AS cluster_dispersion,
            avg(cf.cf_mwr_period_pct) AS cf_basket_return_pct,
            max(cf.own_return) AS own_return,
            max(cf.own_status) AS own_status,
            array_agg(cf.member_symbol ORDER BY cf.member_symbol) FILTER (WHERE cf.cf_mwr_period_pct IS NOT NULL) AS cluster_members,
            count(*) FILTER (WHERE cf.cf_mwr_period_pct IS NOT NULL AND cf.cf_mwr_period_pct > cf.own_return::double precision) + 1 AS rank_raw
           FROM cf
          GROUP BY cf.symbol, cf.asset_id
        ), best AS (
         SELECT DISTINCT ON (cf.symbol) cf.symbol,
            cf.member_symbol AS cf_best_symbol
           FROM cf
          WHERE cf.cf_mwr_period_pct IS NOT NULL
          ORDER BY cf.symbol, cf.cf_mwr_period_pct DESC
        )
 SELECT a.asset_id,
    a.symbol,
    a.cluster_size_nominal,
    a.cluster_size,
    a.avg_intra_rho,
    a.cluster_size >= 5 AND a.avg_intra_rho >= 0.75 AS cluster_eligible,
    0.75 AS cluster_threshold_rho,
    a.cf_median_return_pct::numeric AS cf_median_return_pct,
    a.cf_best_return_pct::numeric AS cf_best_return_pct,
    b.cf_best_symbol,
    a.cf_basket_return_pct::numeric AS cf_basket_return_pct,
    a.cluster_dispersion::numeric AS cluster_dispersion,
        CASE
            WHEN a.cluster_size >= 5 AND a.avg_intra_rho >= 0.75 AND r.engine_status = 'measured'::text AND r.position_mwr_period_pct IS NOT NULL AND a.cf_median_return_pct IS NOT NULL THEN (r.position_mwr_period_pct::double precision - a.cf_median_return_pct)::numeric
            ELSE NULL::numeric
        END AS selection_effect_pct,
        CASE
            WHEN a.cluster_size >= 5 AND a.avg_intra_rho >= 0.75 AND r.engine_status = 'measured'::text AND r.position_mwr_period_pct IS NOT NULL AND a.cf_best_return_pct IS NOT NULL THEN (r.position_mwr_period_pct::double precision - a.cf_best_return_pct)::numeric
            ELSE NULL::numeric
        END AS regret_vs_best_pct,
        CASE
            WHEN a.cluster_dispersion > 0::double precision AND a.cluster_size >= 5 AND a.avg_intra_rho >= 0.75 AND r.engine_status = 'measured'::text AND r.position_mwr_period_pct IS NOT NULL AND a.cf_median_return_pct IS NOT NULL THEN ((r.position_mwr_period_pct::double precision - a.cf_median_return_pct) / a.cluster_dispersion)::numeric
            ELSE NULL::numeric
        END AS selection_effect_vol_adj,
    ( SELECT max(m2.correlation_as_of) AS max
           FROM vw_position_cluster_members m2
          WHERE m2.symbol = a.symbol) AS correlation_as_of,
        CASE
            WHEN a.cluster_size >= 5 AND a.avg_intra_rho >= 0.75 AND a.own_status = 'measured'::text AND a.own_return IS NOT NULL THEN a.rank_raw
            ELSE NULL::bigint
        END AS rank_in_cluster,
        CASE
            WHEN a.cluster_size >= 5 AND a.avg_intra_rho >= 0.75 THEN a.cluster_members
            ELSE NULL::text[]
        END AS cluster_members
   FROM agg a
     LEFT JOIN best b ON b.symbol = a.symbol
     LEFT JOIN ( SELECT mv_position_returns.asset_id,
            mv_position_returns.symbol,
            mv_position_returns.position_state,
            mv_position_returns.engine_status,
            mv_position_returns.engine_reason,
            mv_position_returns.first_flow_date,
            mv_position_returns.last_trade_date,
            mv_position_returns.schedule_end_date,
            mv_position_returns.days_held,
            mv_position_returns.n_buys,
            mv_position_returns.n_sells,
            mv_position_returns.net_qty,
            mv_position_returns.broker_qty,
            mv_position_returns.capital_deployed_usd,
            mv_position_returns.proceeds_usd,
            mv_position_returns.terminal_value_usd,
            mv_position_returns.net_pnl_usd,
            mv_position_returns.simple_return_pct,
            mv_position_returns.position_mwr_period_pct,
            mv_position_returns.position_mwr_close_basis_pct,
            mv_position_returns.execution_effect_pp,
            mv_position_returns.position_mwr_pct,
            mv_position_returns.mwr_annualisable,
            mv_position_returns.position_twr_pct,
            mv_position_returns.window_open_price,
            mv_position_returns.window_close_price,
            mv_position_returns.mark_days_old,
            mv_position_returns.mark_price_date,
            mv_position_returns.ledger_complete,
            mv_position_returns.broker_reconciles,
            mv_position_returns.flow_dates,
            mv_position_returns.flow_amounts,
            mv_position_returns.computed_at
           FROM mv_position_returns) r ON r.asset_id = a.asset_id;
-- vw_position_tier2: 2 guard(s) removed
create or replace view public.vw_position_tier2 as
 WITH latest_corr AS (
         SELECT max(universe_correlations.as_of_date) AS d
           FROM universe_correlations
        ), open_book AS (
         SELECT DISTINCT mv_position_returns.symbol
           FROM ( SELECT mv_position_returns_1.asset_id,
                    mv_position_returns_1.symbol,
                    mv_position_returns_1.position_state,
                    mv_position_returns_1.engine_status,
                    mv_position_returns_1.engine_reason,
                    mv_position_returns_1.first_flow_date,
                    mv_position_returns_1.last_trade_date,
                    mv_position_returns_1.schedule_end_date,
                    mv_position_returns_1.days_held,
                    mv_position_returns_1.n_buys,
                    mv_position_returns_1.n_sells,
                    mv_position_returns_1.net_qty,
                    mv_position_returns_1.broker_qty,
                    mv_position_returns_1.capital_deployed_usd,
                    mv_position_returns_1.proceeds_usd,
                    mv_position_returns_1.terminal_value_usd,
                    mv_position_returns_1.net_pnl_usd,
                    mv_position_returns_1.simple_return_pct,
                    mv_position_returns_1.position_mwr_period_pct,
                    mv_position_returns_1.position_mwr_close_basis_pct,
                    mv_position_returns_1.execution_effect_pp,
                    mv_position_returns_1.position_mwr_pct,
                    mv_position_returns_1.mwr_annualisable,
                    mv_position_returns_1.position_twr_pct,
                    mv_position_returns_1.window_open_price,
                    mv_position_returns_1.window_close_price,
                    mv_position_returns_1.mark_days_old,
                    mv_position_returns_1.mark_price_date,
                    mv_position_returns_1.ledger_complete,
                    mv_position_returns_1.broker_reconciles,
                    mv_position_returns_1.flow_dates,
                    mv_position_returns_1.flow_amounts,
                    mv_position_returns_1.computed_at
                   FROM mv_position_returns mv_position_returns_1) mv_position_returns
          WHERE mv_position_returns.position_state = 'open'::text
        ), pairs AS (
         SELECT c_1.symbol_1 AS sym,
            c_1.symbol_2 AS other,
            c_1.correlation AS rho
           FROM universe_correlations c_1,
            latest_corr l
          WHERE c_1.as_of_date = l.d AND c_1.correlation IS NOT NULL AND (c_1.symbol_2 IN ( SELECT open_book.symbol
                   FROM open_book))
        UNION ALL
         SELECT c_1.symbol_2,
            c_1.symbol_1,
            c_1.correlation
           FROM universe_correlations c_1,
            latest_corr l
          WHERE c_1.as_of_date = l.d AND c_1.correlation IS NOT NULL AND (c_1.symbol_1 IN ( SELECT open_book.symbol
                   FROM open_book))
        ), best AS (
         SELECT DISTINCT ON (p.sym) p.sym,
            p.other,
            p.rho
           FROM pairs p
             JOIN open_book o ON o.symbol = p.sym
          WHERE p.other <> p.sym
          ORDER BY p.sym, p.rho DESC
        )
 SELECT r.asset_id,
    r.symbol,
    r.position_state,
    r.engine_status,
    r.engine_reason,
    r.position_mwr_period_pct,
    c.cf_mwr_period_pct AS cf_book_return_pct,
    c.cf_capital_deployed_usd AS cf_book_capital_deployed_usd,
    c.cf_net_pnl_usd AS cf_book_net_pnl_usd,
    c.cf_status AS cf_book_status,
    c.cf_reason AS cf_book_reason,
        CASE
            WHEN r.engine_status = 'measured'::text AND c.cf_status = 'measured'::text AND r.position_mwr_period_pct IS NOT NULL AND c.cf_mwr_period_pct IS NOT NULL THEN (r.position_mwr_period_pct::double precision - c.cf_mwr_period_pct)::numeric
            ELSE NULL::numeric
        END AS excess_vs_book_pct,
    b.rho AS best_correlate_rho,
    b.other AS best_correlate_symbol,
    r.position_state = 'open'::text AND NOT (EXISTS ( SELECT 1
           FROM universe_correlations c2,
            latest_corr l2
          WHERE c2.as_of_date = l2.d AND (c2.symbol_1 = r.symbol OR c2.symbol_2 = r.symbol))) AS absent_from_matrix,
    ( SELECT latest_corr.d
           FROM latest_corr) AS correlation_as_of
   FROM ( SELECT mv_position_returns.asset_id,
            mv_position_returns.symbol,
            mv_position_returns.position_state,
            mv_position_returns.engine_status,
            mv_position_returns.engine_reason,
            mv_position_returns.first_flow_date,
            mv_position_returns.last_trade_date,
            mv_position_returns.schedule_end_date,
            mv_position_returns.days_held,
            mv_position_returns.n_buys,
            mv_position_returns.n_sells,
            mv_position_returns.net_qty,
            mv_position_returns.broker_qty,
            mv_position_returns.capital_deployed_usd,
            mv_position_returns.proceeds_usd,
            mv_position_returns.terminal_value_usd,
            mv_position_returns.net_pnl_usd,
            mv_position_returns.simple_return_pct,
            mv_position_returns.position_mwr_period_pct,
            mv_position_returns.position_mwr_close_basis_pct,
            mv_position_returns.execution_effect_pp,
            mv_position_returns.position_mwr_pct,
            mv_position_returns.mwr_annualisable,
            mv_position_returns.position_twr_pct,
            mv_position_returns.window_open_price,
            mv_position_returns.window_close_price,
            mv_position_returns.mark_days_old,
            mv_position_returns.mark_price_date,
            mv_position_returns.ledger_complete,
            mv_position_returns.broker_reconciles,
            mv_position_returns.flow_dates,
            mv_position_returns.flow_amounts,
            mv_position_returns.computed_at
           FROM mv_position_returns) r
     CROSS JOIN LATERAL atlas_counterfactual_book(r.asset_id) c(cf_capital_deployed_usd, cf_proceeds_usd, cf_terminal_value_usd, cf_net_pnl_usd, cf_mwr_period_pct, cf_status, cf_reason)
     LEFT JOIN best b ON b.sym = r.symbol;
-- vw_book_frozen_baseline: 2 guard(s) removed
create or replace view public.vw_book_frozen_baseline as
 WITH val AS (
         SELECT max(c.flow_date) AS val_dt
           FROM vw_position_cash_flows c
          WHERE c.flow_kind = 'mark'::text
        ), eligible AS (
         SELECT p.asset_id,
            p.frozen_entry_date,
            p.frozen_capital_usd,
            p.frozen_terminal_usd
           FROM vw_position_frozen p
          WHERE p.trading_effect_pct IS NOT NULL
        ), traded_flows AS (
         SELECT c.flow_date AS d,
            c.flow_usd AS amt
           FROM vw_position_cash_flows c
             JOIN eligible e ON e.asset_id = c.asset_id
        ), frozen_flows AS (
         SELECT e.frozen_entry_date AS d,
            - e.frozen_capital_usd AS amt
           FROM eligible e
        UNION ALL
         SELECT ( SELECT val.val_dt
                   FROM val) AS val_dt,
            e.frozen_terminal_usd
           FROM eligible e
        ), traded AS (
         SELECT array_agg(traded_flows.d ORDER BY traded_flows.d) AS ds,
            array_agg(traded_flows.amt ORDER BY traded_flows.d) AS amts
           FROM traded_flows
        ), frozen AS (
         SELECT array_agg(frozen_flows.d ORDER BY frozen_flows.d) AS ds,
            array_agg(frozen_flows.amt ORDER BY frozen_flows.d) AS amts
           FROM frozen_flows
        )
 SELECT ( SELECT val.val_dt
           FROM val) AS as_of,
    ( SELECT count(*) AS count
           FROM eligible) AS positions_compared,
    atlas_mwr_period(t.ds, t.amts)::numeric AS traded_book_return_pct,
    atlas_mwr_period(f.ds, f.amts)::numeric AS frozen_book_return_pct,
    (atlas_mwr_period(t.ds, t.amts) - atlas_mwr_period(f.ds, f.amts))::numeric AS trading_effect_pct,
    ( SELECT count(*) AS count
           FROM ( SELECT mv_position_tier1_1.asset_id,
                    mv_position_tier1_1.symbol,
                    mv_position_tier1_1.cluster_size_nominal,
                    mv_position_tier1_1.cluster_size,
                    mv_position_tier1_1.avg_intra_rho,
                    mv_position_tier1_1.cluster_eligible,
                    mv_position_tier1_1.cluster_threshold_rho,
                    mv_position_tier1_1.cf_median_return_pct,
                    mv_position_tier1_1.cf_best_return_pct,
                    mv_position_tier1_1.cf_best_symbol,
                    mv_position_tier1_1.cf_basket_return_pct,
                    mv_position_tier1_1.cluster_dispersion,
                    mv_position_tier1_1.selection_effect_pct,
                    mv_position_tier1_1.regret_vs_best_pct,
                    mv_position_tier1_1.selection_effect_vol_adj,
                    mv_position_tier1_1.correlation_as_of,
                    mv_position_tier1_1.rank_in_cluster,
                    mv_position_tier1_1.cluster_members,
                    mv_position_tier1_1.computed_at
                   FROM mv_position_tier1 mv_position_tier1_1) mv_position_tier1
          WHERE mv_position_tier1.cluster_eligible) AS positions_cluster_eligible,
    ( SELECT count(*) AS count
           FROM ( SELECT mv_position_tier2_1.asset_id,
                    mv_position_tier2_1.symbol,
                    mv_position_tier2_1.position_state,
                    mv_position_tier2_1.engine_status,
                    mv_position_tier2_1.engine_reason,
                    mv_position_tier2_1.position_mwr_period_pct,
                    mv_position_tier2_1.cf_book_return_pct,
                    mv_position_tier2_1.cf_book_capital_deployed_usd,
                    mv_position_tier2_1.cf_book_net_pnl_usd,
                    mv_position_tier2_1.cf_book_status,
                    mv_position_tier2_1.cf_book_reason,
                    mv_position_tier2_1.excess_vs_book_pct,
                    mv_position_tier2_1.best_correlate_rho,
                    mv_position_tier2_1.best_correlate_symbol,
                    mv_position_tier2_1.absent_from_matrix,
                    mv_position_tier2_1.correlation_as_of,
                    mv_position_tier2_1.computed_at
                   FROM mv_position_tier2 mv_position_tier2_1) mv_position_tier2
          WHERE mv_position_tier2.position_state = 'open'::text AND (mv_position_tier2.best_correlate_rho IS NULL OR mv_position_tier2.best_correlate_rho < 0.65)) AS positions_no_correlate
   FROM traded t,
    frozen f;
-- 10 guards removed in all

-- 6. drop the retired matviews
drop materialized view public.mv_book_daily_weights__retired, public.mv_book_ex_index__retired, public.mv_position_returns__retired, public.mv_position_tier2__retired, public.mv_position_tier1__retired, public.mv_segment_ex_index__retired;

-- ------------------------------------------------------------------------
-- 7. Refresh = recompute for the ACTIVE account, then per account
-- ------------------------------------------------------------------------
-- Replaces REFRESH MATERIALIZED VIEW. Recomputes the named entries, in the
-- order given, for whichever account the request header names (the default
-- when there is none). Callers that want every account loop and set the
-- header themselves, as atlas_refresh_verdict_inputs does below.
create or replace function public.atlas_rematerialise(p_names text[])
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_pid   uuid := public.atlas_active_portfolio();
  v_name  text;
  v_n     int;
  v_out   jsonb := '{}'::jsonb;
begin
  foreach v_name in array p_names loop
    if v_name <> all (array['mv_book_daily_weights','mv_book_ex_index','mv_position_returns',
                            'mv_position_tier1','mv_position_tier2','mv_segment_ex_index']) then
      raise exception 'atlas_rematerialise: % is not a per-account materialisation', v_name;
    end if;
    -- One transaction: a reader sees the previous rows until commit, the
    -- property REFRESH ... CONCURRENTLY was used for.
    execute format('delete from public.%I where portfolio_id = $1', v_name || '__acct') using v_pid;
    execute format('insert into public.%I select $1, c.* from public.%I c',
                   v_name || '__acct', v_name || '__compute') using v_pid;
    get diagnostics v_n = row_count;
    v_out := v_out || jsonb_build_object(v_name, v_n);
  end loop;
  return v_out;
end
$fn$;

-- Every account, each in its own subtransaction and with its own sync_log
-- row: one account failing neither blocks nor rolls back the other.
create or replace function public.atlas_rematerialise_all(p_names text[], p_label text)
returns void
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_orig  text := current_setting('request.headers', true);
  r       record;
  v_log   bigint;
  v_rows  jsonb;
begin
  for r in select p.id, p.name from public.portfolios p order by p.is_default desc, p.name loop
    insert into public.sync_log (function_name, source, status, portfolio_id, started_at, details)
    values (p_label, 'pg_cron', 'running', r.id, clock_timestamp(),
            jsonb_build_object('portfolio', r.name, 'names', p_names))
    returning id into v_log;
    begin
      perform set_config('request.headers',
                         json_build_object('x-atlas-portfolio', r.id::text)::text, true);
      v_rows := public.atlas_rematerialise(p_names);
      update public.sync_log
         set status = 'success', finished_at = clock_timestamp(),
             details = details || jsonb_build_object('rows', v_rows)
       where id = v_log;
    exception when others then
      update public.sync_log
         set status = 'error', finished_at = clock_timestamp(), error_message = sqlerrm
       where id = v_log;
    end;
  end loop;
  perform set_config('request.headers', coalesce(v_orig, ''), true);
end
$fn$;

create or replace function public.atlas_refresh_verdict_inputs()
 returns void
 language plpgsql
 security definer
 set search_path to 'public'
as $fn$
begin
  -- Dependency order. mv_book_ex_index reads mv_book_daily_weights; both
  -- tier views read mv_position_returns; tier2 also reads mv_book_ex_index.
  perform public.atlas_rematerialise_all(
    array['mv_book_daily_weights','mv_book_ex_index','mv_position_returns',
          'mv_position_tier2','mv_position_tier1'],
    'refresh_verdict_inputs');
end
$fn$;

create or replace function public.atlas_refresh_position_returns()
 returns void
 language plpgsql
 security definer
 set search_path to 'public'
as $fn$
begin
  perform public.atlas_rematerialise_all(array['mv_position_returns'], 'refresh_position_returns');
end
$fn$;

revoke execute on function public.atlas_rematerialise(text[]) from public, anon, authenticated;
revoke execute on function public.atlas_rematerialise_all(text[], text) from public, anon, authenticated;
revoke execute on function public.atlas_refresh_verdict_inputs() from public, anon, authenticated;
revoke execute on function public.atlas_refresh_position_returns() from public, anon, authenticated;

-- ------------------------------------------------------------------------
-- 8. The histories carry the account they describe
-- ------------------------------------------------------------------------
-- Existing rows were all written for the default account (the job ran
-- headerless); the default backfills them to exactly that.
alter table public.position_verdicts
  add column portfolio_id uuid not null default public.atlas_default_portfolio()
      references public.portfolios(id);
alter table public.position_verdicts
  drop constraint position_verdicts_as_of_asset_id_logic_version_key,
  add constraint position_verdicts_key unique (portfolio_id, as_of, asset_id, logic_version);
drop index if exists public.position_verdicts_as_of_version_idx;
drop index if exists public.position_verdicts_asset_as_of_idx;
create index position_verdicts_as_of_version_idx
  on public.position_verdicts (portfolio_id, as_of desc, logic_version);
create index position_verdicts_asset_as_of_idx
  on public.position_verdicts (portfolio_id, asset_id, as_of desc);

alter table public.segment_verdicts
  add column portfolio_id uuid not null default public.atlas_default_portfolio()
      references public.portfolios(id);
alter table public.segment_verdicts
  drop constraint segment_verdicts_key,
  add constraint segment_verdicts_key unique (portfolio_id, as_of, logic_version, "grouping", segment_id);
drop index if exists public.segment_verdicts_as_of_grouping_idx;
create index segment_verdicts_as_of_grouping_idx
  on public.segment_verdicts (portfolio_id, as_of desc, "grouping", risk_share desc);

-- Was: visible only on the default account. Now: the active account's own.
drop policy position_verdicts_read on public.position_verdicts;
create policy position_verdicts_read on public.position_verdicts
  for select to anon, authenticated
  using (portfolio_id = (select public.atlas_active_portfolio()));
drop policy segment_verdicts_read on public.segment_verdicts;
create policy segment_verdicts_read on public.segment_verdicts
  for select to anon, authenticated
  using (portfolio_id = (select public.atlas_active_portfolio()));

-- ------------------------------------------------------------------------
-- 9. The per-account writers: the previous bodies, scoped to the active account
-- ------------------------------------------------------------------------
-- Edits (gen5c.py, each asserted by count): portfolio_id on every read and
-- write of position_verdicts / segment_verdicts / book_risk_daily / sync_log;
-- REFRESH replaced by atlas_rematerialise; a preflight refusal RETURNs instead
-- of RAISEing, so its log row survives.

CREATE OR REPLACE FUNCTION public.atlas_write_verdicts_active(p_as_of date DEFAULT NULL::date, p_logic_version text DEFAULT 'v1:rho0.75:n5:mwr'::text, p_refresh boolean DEFAULT true)
 RETURNS TABLE(out_as_of date, out_logic_version text, out_rows_written integer, out_notes text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
    v_as_of        date;
    v_pos_as_of    date;
    v_last_traded  date;
    v_written      int;
    v_share_sum    numeric;
    v_bad          int;
    v_note         text := '';
    v_log_id       bigint;
    v_pre          jsonb;
    v_failed       text;
    v_existing     int;
    -- MP-5: every row this function reads or writes belongs to the ACTIVE
    -- account. The public atlas_write_verdicts() sets the header per account.
    v_pid          uuid := public.atlas_active_portfolio();
BEGIN
    IF p_refresh THEN
        PERFORM public.atlas_rematerialise(ARRAY['mv_book_daily_weights','mv_book_ex_index',
                                                 'mv_position_returns','mv_position_tier2',
                                                 'mv_position_tier1']);
    END IF;

    v_as_of       := COALESCE(p_as_of, CURRENT_DATE);
    v_pos_as_of   := (SELECT max(pz.as_of_date) FROM public.vw_active_positions pz);
    v_last_traded := public.atlas_last_traded_day();

    INSERT INTO public.sync_log (source, function_name, status, portfolio_id, started_at, details)
    VALUES ('atlas_write_verdicts', 'atlas_write_verdicts', 'running', v_pid, now(),
            jsonb_build_object('as_of', v_as_of, 'logic_version', p_logic_version))
    RETURNING id INTO v_log_id;

    -- ------------------------------------------------------------------
    -- Rev. B §6, last invariant: no verdict row while any position carries
    -- a stale broker row. `position_verdicts` is a history and a row written
    -- against yesterday's book freezes the wrong holdings into the record
    -- permanently - which is exactly the §1 blocker that gated this whole
    -- step. A view recomputes; a history does not.
    -- ------------------------------------------------------------------
    SELECT jsonb_agg(jsonb_build_object('check', check_name, 'passed', passed, 'detail', detail)),
           string_agg(check_name || ': ' || detail, '; ') FILTER (WHERE NOT passed)
      INTO v_pre, v_failed
      FROM public.atlas_verdict_preflight();

    IF v_failed IS NOT NULL THEN
        UPDATE public.sync_log
           SET status = 'skipped', finished_at = now(),
               details = details || jsonb_build_object('reason', 'preflight failed',
                                                      'preflight', v_pre)
         WHERE id = v_log_id;
        -- Refuse by RETURNING, not RAISE: a RAISE rolls back the log row that
        -- records the refusal, and the wrapper runs every account in its own
        -- subtransaction.
        RETURN QUERY SELECT v_as_of, p_logic_version, 0, 'preflight failed: ' || v_failed;
        RETURN;
    END IF;

    -- ------------------------------------------------------------------
    -- The rows
    -- ------------------------------------------------------------------
    WITH open_book AS (
        SELECT r.* FROM public.mv_position_returns r WHERE r.position_state = 'open'
    ),
    risk AS (
        -- Renormalised over the positions we actually rank. vw_risk_analysis
        -- carries 79 rows for 57 open names and its weights sum to 1.0157;
        -- the difference is written out as `residual` rather than absorbed.
        SELECT v.symbol, v.annual_vol, v.dollar_var_95_daily,
               v.weight / NULLIF(sum(v.weight) OVER (), 0) AS w_norm
          FROM public.vw_risk_analysis v
         WHERE v.symbol IN (SELECT symbol FROM open_book)
    ),
    -- defect 3. vw_risk_analysis.marginal_vol_contribution is weight * vol --
    -- no covariance, so positive by construction and with no Euler
    -- additivity. mctr_annual is the real partial derivative and
    -- risk_contribution_annual is already mctr x weight. One scan; the view
    -- is ~340-450 ms.
    mctr AS (
        SELECT m.symbol, m.mctr_annual, m.risk_contribution_annual, m.matrix_as_of
          FROM public.vw_book_mctr m
         WHERE m.symbol IN (SELECT symbol FROM open_book)
    ),
    mx AS (SELECT max(matrix_as_of) AS d FROM mctr),
    clus AS (
        SELECT u.symbol, u.cluster_id
          FROM public.universe_clusters u
         WHERE u.as_of_date = (SELECT max(u2.as_of_date) FROM public.universe_clusters u2)
    ),
    -- Risk share is computed over a PARTITION (universe_clusters), not over
    -- Tier 1's rho >= 0.75 neighbourhood. They are different objects: a
    -- neighbourhood overlaps and covers 17 names, a partition covers the book
    -- and sums to 1. Conflating them is what would break the identity.
    share AS (
        SELECT c.cluster_id,
               sum(mc.risk_contribution_annual) AS contrib
          FROM mctr mc JOIN clus c ON c.symbol = mc.symbol
         GROUP BY c.cluster_id
    ),
    share_n AS (
        SELECT cluster_id, contrib / NULLIF(sum(contrib) OVER (), 0) AS cluster_risk_share
          FROM share
    ),
    -- The cluster leader must not be a leveraged product. SOXL tops five of
    -- the seventeen eligible clusters because a 3x fund takes a levered share
    -- of any move that went the right way; "switch to SOXL" is not advice this
    -- module should be able to emit. Gated on measured volatility rather than
    -- a name match: a leader more than 1.5x the position's own vol is not a
    -- like-for-like substitute whatever it is called.
    leader_vol AS (
        SELECT t.symbol,
               t.cf_best_symbol,
               (SELECT stddev_samp(x.r) * sqrt(252::numeric)
                  FROM (SELECT ph.close / lag(ph.close) OVER (ORDER BY ph.price_date) - 1 AS r
                          FROM public.price_history ph
                          JOIN public.vw_canonical_assets ca ON ca.asset_id = ph.asset_id
                         WHERE ca.symbol = t.cf_best_symbol AND ph."interval" = '1d'
                           AND ph.price_date > v_as_of - 180
                       ) x
                 WHERE x.r IS NOT NULL) AS lead_vol
          FROM public.mv_position_tier1 t
         WHERE t.cluster_eligible AND t.cf_best_symbol IS NOT NULL
    ),
    assembled AS (
        SELECT o.asset_id,
               o.symbol,
               o.position_state,
               COALESCE(p.side, 'long')                                AS side,
               o.engine_status,
               o.engine_reason,
               o.days_held,
               o.first_flow_date,
               o.capital_deployed_usd,
               o.position_mwr_pct,
               o.position_twr_pct,
               o.mark_days_old,
               o.mark_price_date,
               CASE o.engine_status
                   WHEN 'measured'        THEN 'measured'
                   WHEN 'stale_mark'      THEN 'stale_mark'
                   WHEN 'ledger_mismatch' THEN 'ledger_mismatch'
                   WHEN 'basis_mismatch'  THEN 'basis_mismatch'
                   ELSE 'one_sided'
               END                                                     AS verdict_status,
               t1.cluster_eligible,
               t1.cluster_size,
               t1.avg_intra_rho,
               cl.cluster_id,   -- partition, not the tier-1 join (spec 2.4c)
               t1.cf_median_return_pct,
               t1.cf_best_return_pct,
               t1.cf_best_symbol,
               t1.cf_basket_return_pct,
               t1.cluster_dispersion,
               t1.rank_in_cluster,
               bt.thesis_state,
               bt.thesis_state_as_of,
               t1.cluster_members,
               t1.selection_effect_pct,
               t1.regret_vs_best_pct,
               t1.selection_effect_vol_adj,
               t2.cf_book_return_pct,
               t2.excess_vs_book_pct,
               t2.best_correlate_rho,
               t2.best_correlate_symbol,
               fz.frozen_weight_return_pct,
               fz.trading_effect_pct,
               rk.annual_vol,
               mc.mctr_annual AS marginal_vol_contribution,
               rk.dollar_var_95_daily,
               sn.cluster_risk_share,
               lv.lead_vol,
               CASE WHEN COALESCE(t1.cluster_eligible, false) THEN 'cluster'
                    WHEN t2.excess_vs_book_pct IS NOT NULL     THEN 'book'
                    ELSE 'none' END                                    AS peer_basis,
               COALESCE(t1.selection_effect_pct, t2.excess_vs_book_pct) AS active_score
          FROM open_book o
          LEFT JOIN (SELECT t.*, c.cluster_id
                       FROM public.mv_position_tier1 t
                       LEFT JOIN clus c ON c.symbol = t.symbol) t1 ON t1.asset_id = o.asset_id
          LEFT JOIN public.mv_position_tier2 t2 ON t2.asset_id = o.asset_id
          LEFT JOIN public.vw_bench_thesis_state bt ON bt.symbol = o.symbol
          LEFT JOIN public.vw_position_frozen fz ON fz.asset_id = o.asset_id
          LEFT JOIN risk    rk ON rk.symbol = o.symbol
          LEFT JOIN mctr    mc ON mc.symbol = o.symbol
          LEFT JOIN clus    cl ON cl.symbol = o.symbol
          LEFT JOIN share_n sn ON sn.cluster_id = cl.cluster_id
          LEFT JOIN leader_vol lv ON lv.symbol = o.symbol
          LEFT JOIN LATERAL (
                SELECT pp.side FROM public.vw_active_positions pp
                 WHERE pp.asset_id = o.asset_id AND pp.as_of_date = v_pos_as_of
                 LIMIT 1) p ON true
    ),
    labelled AS (
        SELECT a.*,
               CASE WHEN a.verdict_status <> 'measured' OR a.active_score IS NULL THEN NULL
                    WHEN a.active_score >=  0.05 THEN 'leader'
                    WHEN a.active_score >  -0.05 THEN 'holding_own'
                    WHEN a.active_score >= -0.20 THEN 'lagging'
                    ELSE 'cut_candidate'
               END AS verdict_label
          FROM assembled a
    )
    INSERT INTO public.position_verdicts (
        portfolio_id, as_of, logic_version, asset_id, symbol, position_state, side,
        verdict_status, status_reason, price_days_old, last_measurable_date,
        first_entry_date, days_held, capital_deployed_usd,
        position_mwr_pct, position_twr_pct, annualised_return,
        peer_basis, cluster_threshold_rho, cluster_id, cluster_size, avg_intra_rho,
        cf_median_return_pct, cf_best_return_pct, cf_best_symbol, cf_basket_return_pct,
        selection_effect_pct, regret_vs_best_pct, selection_effect_vol_adj,
        position_vol_annual, marginal_vol_contribution, dollar_var_95_daily,
        cluster_risk_share, verdict_label, suggested_reason_code,
        ranking_basis, engine_status, status_detail,
        cluster_eligible, cf_book_return_pct, excess_vs_book_pct,
        best_correlate_rho, best_correlate_symbol,
        frozen_weight_return_pct, trading_effect_pct, cluster_dispersion,
        rank_in_cluster, cluster_members,
        thesis_state, thesis_state_as_of,
        evidence_own_return_known, evidence_staleness_days,
        risk_basis, risk_matrix_as_of)
    SELECT v_pid, v_as_of, p_logic_version, l.asset_id, l.symbol, l.position_state, l.side,
           l.verdict_status, l.engine_reason, l.mark_days_old, l.mark_price_date,
           l.first_flow_date, l.days_held, l.capital_deployed_usd,
           l.position_mwr_pct, l.position_twr_pct,
           -- §2.7 floor. Also a CHECK; asserted here so the job fails loudly
           -- rather than the constraint firing on a row nobody looked at.
           CASE WHEN l.days_held >= 90 THEN l.position_mwr_pct END,
           l.peer_basis, 0.75, l.cluster_id, l.cluster_size, l.avg_intra_rho,
           l.cf_median_return_pct, l.cf_best_return_pct, l.cf_best_symbol, l.cf_basket_return_pct,
           l.selection_effect_pct, l.regret_vs_best_pct, l.selection_effect_vol_adj,
           l.annual_vol, l.marginal_vol_contribution, l.dollar_var_95_daily,
           l.cluster_risk_share, l.verdict_label,
           CASE
               WHEN l.verdict_label = 'cut_candidate' AND l.peer_basis = 'cluster'
                    AND l.cf_best_symbol IS NOT NULL
                    AND l.lead_vol IS NOT NULL AND l.annual_vol IS NOT NULL
                    AND l.lead_vol <= 1.5 * l.annual_vol
                    THEN 'switch_to_cluster_leader'
               WHEN l.verdict_label = 'cut_candidate' AND l.peer_basis = 'cluster'
                    THEN 'cut_underperforming_comparables'
               WHEN l.verdict_label = 'cut_candidate' AND l.peer_basis = 'book'
                    THEN 'trim_concentration'
           END,
           'mwr', l.engine_status, l.engine_reason,
           COALESCE(l.cluster_eligible, false), l.cf_book_return_pct, l.excess_vs_book_pct,
           l.best_correlate_rho, l.best_correlate_symbol,
           l.frozen_weight_return_pct, l.trading_effect_pct, l.cluster_dispersion,
           l.rank_in_cluster, l.cluster_members,
           l.thesis_state, l.thesis_state_as_of,
           (l.verdict_status = 'measured'), l.mark_days_old,
           -- The basis is NULL exactly when both figures are, which the CHECK
           -- enforces as a CASE rather than an OR chain: an OR chain of `=`
           -- comparisons yields NULL on a NULL basis, and a CHECK PASSES on
           -- NULL.
           CASE WHEN l.marginal_vol_contribution IS NULL
                 AND l.cluster_risk_share IS NULL THEN NULL ELSE 'mctr_euler' END,
           CASE WHEN l.marginal_vol_contribution IS NULL
                 AND l.cluster_risk_share IS NULL THEN NULL ELSE mx.d END
      FROM labelled l
      CROSS JOIN mx
    ON CONFLICT (portfolio_id, as_of, asset_id, logic_version) DO NOTHING;

    GET DIAGNOSTICS v_written = ROW_COUNT;

    -- ------------------------------------------------------------------
    -- Rev. B §6, the cross-row invariants. The single-row ones are CHECKs
    -- on the table and cannot be forgotten; these two cannot be CHECKs.
    -- ------------------------------------------------------------------
    SELECT sum(s.share) INTO v_share_sum
      FROM (SELECT DISTINCT coalesce(pv.cluster_id::text, 'pos:' || pv.asset_id::text) AS bucket,
                   pv.cluster_risk_share AS share
              FROM public.position_verdicts pv
             WHERE pv.portfolio_id = v_pid AND pv.as_of = v_as_of AND pv.logic_version = p_logic_version
               AND pv.cluster_risk_share IS NOT NULL) s;

    IF v_share_sum IS NOT NULL AND abs(v_share_sum - 1.0) > 0.005 THEN
        RAISE EXCEPTION 'cluster_risk_share sums to % across the book, not 1.0', v_share_sum;
    END IF;

    SELECT count(*) INTO v_bad
      FROM public.position_verdicts
     WHERE portfolio_id = v_pid AND as_of = v_as_of AND logic_version = p_logic_version
       AND peer_basis = 'none' AND verdict_status = 'measured';
    IF v_bad > 0 THEN
        v_note := v_note || v_bad::text || ' measured positions have no basis; ';
    END IF;

    -- ------------------------------------------------------------------
    -- Book companion
    -- ------------------------------------------------------------------
    INSERT INTO public.book_risk_daily (
        portfolio_id, as_of, logic_version, total_vol_annual, book_var_95_daily,
        sum_contributions, residual, effective_bets, cluster_shares,
        unmapped_theme_weight, cluster_threshold_rho,
        traded_book_return_pct, frozen_book_return_pct, trading_effect_pct,
        positions_cluster_eligible, positions_no_correlate,
        positions_in_matrix, positions_absent_from_matrix,
        vol_basis, vol_matrix_as_of)
    SELECT v_pid, v_as_of, p_logic_version,
           -- Was sum(mvc * weight) * sqrt(252). mvc is already weight * ANNUAL
           -- vol, so that squared the weight AND re-annualised an annual figure
           -- -- two dimensional errors that partly cancelled into a
           -- plausible-looking 10.78% against a true ~19.5%. Read the real
           -- Euler-additive book vol instead (Sigma = D R D, B4).
           mc.vol,
           (SELECT sum(v.dollar_var_95_daily) FROM public.vw_risk_analysis v
             WHERE v.symbol IN (SELECT pv.symbol FROM public.position_verdicts pv
                                 WHERE pv.portfolio_id = v_pid AND pv.as_of = v_as_of AND pv.logic_version = p_logic_version)),
           -- Sum of the Euler risk contributions over the ranked book. Under
           -- MCTR this SUMS TO THE BOOK VOL by construction, so the pair
           -- (sum_contributions, residual) is an identity rather than the
           -- dimensionless product of a per-position figure and a per-cluster
           -- share that stood here before.
           (SELECT sum(m.risk_contribution_annual) FROM public.vw_book_mctr m
             WHERE m.symbol IN (SELECT pv.symbol FROM public.position_verdicts pv
                                 WHERE pv.portfolio_id = v_pid AND pv.as_of = v_as_of AND pv.logic_version = p_logic_version)),
           -- Written out, never swept up (memo v2 §2.8): the gap between the
           -- whole risk view and the positions actually ranked.
           -- The book vol the ranked positions do NOT account for: names the
           -- correlation matrix cannot price. Written out, never swept up.
           mc.vol - (SELECT COALESCE(sum(m.risk_contribution_annual), 0)
                       FROM public.vw_book_mctr m
                      WHERE m.symbol IN (SELECT pv.symbol FROM public.position_verdicts pv
                                          WHERE pv.portfolio_id = v_pid AND pv.as_of = v_as_of
                                            AND pv.logic_version = p_logic_version)),
           (SELECT 1.0 / NULLIF(sum(s.share * s.share), 0)
              FROM (SELECT DISTINCT cluster_id, cluster_risk_share AS share
                      FROM public.position_verdicts
                     WHERE portfolio_id = v_pid AND as_of = v_as_of AND logic_version = p_logic_version
                       AND cluster_risk_share IS NOT NULL) s),
           (SELECT jsonb_object_agg(s.cluster_id::text, round(s.share, 6))
              FROM (SELECT DISTINCT cluster_id, cluster_risk_share AS share
                      FROM public.position_verdicts
                     WHERE portfolio_id = v_pid AND as_of = v_as_of AND logic_version = p_logic_version
                       AND cluster_risk_share IS NOT NULL AND cluster_id IS NOT NULL) s),
           (SELECT COALESCE(sum(v.weight) FILTER (
                     WHERE NOT EXISTS (SELECT 1 FROM public.position_themes pt
                                        WHERE pt.symbol = v.symbol AND pt.theme IS NOT NULL)), 0)
                   / NULLIF(sum(v.weight), 0)
              FROM public.vw_risk_analysis v
             WHERE v.symbol IN (SELECT pv.symbol FROM public.position_verdicts pv
                                 WHERE pv.portfolio_id = v_pid AND pv.as_of = v_as_of AND pv.logic_version = p_logic_version)),
           0.75,
           b.traded_book_return_pct, b.frozen_book_return_pct, b.trading_effect_pct,
           b.positions_cluster_eligible, b.positions_no_correlate,
           (SELECT count(*) FROM public.position_verdicts pv
             WHERE pv.portfolio_id = v_pid AND pv.as_of = v_as_of AND pv.logic_version = p_logic_version
               AND pv.best_correlate_rho IS NOT NULL),
           (SELECT count(*) FROM public.vw_held_symbols_absent_from_matrix),
           -- The basis is NULL exactly when the figure is, so a row can never
           -- claim a method for a number it does not have.
           CASE WHEN mc.vol IS NULL THEN NULL ELSE 'mctr_covariance' END,
           mc.mx
      FROM public.vw_book_frozen_baseline b
      -- One scan, not three: vw_book_mctr is ~340-450 ms and this file's own
      -- history records a view re-derived per reference costing 2,768 ms.
      LEFT JOIN LATERAL (
          SELECT max(m.book_vol_annual)::numeric AS vol,
                 max(m.matrix_as_of)            AS mx
            FROM public.vw_book_mctr m
      ) mc ON true
    ON CONFLICT (portfolio_id, as_of, logic_version) DO NOTHING;

    SELECT count(*) INTO v_existing
      FROM public.position_verdicts pv
     WHERE pv.portfolio_id = v_pid AND pv.as_of = v_as_of AND pv.logic_version = p_logic_version;

    IF v_written = 0 AND v_existing = 0 THEN
        UPDATE public.sync_log
           SET status = 'error', finished_at = now(),
               error_message = 'wrote no verdict rows and none exist for this as_of',
               details = details || jsonb_build_object('preflight', v_pre)
         WHERE id = v_log_id;
        RAISE EXCEPTION 'verdict job produced no rows for % / % and none exist',
                        v_as_of, p_logic_version;
    END IF;

    UPDATE public.sync_log
       SET status = CASE WHEN v_written = 0 THEN 'skipped' ELSE 'success' END,
           finished_at = now(),
           error_message = CASE WHEN v_written = 0
                                THEN 'already written for this as_of' END,
           details = details || jsonb_build_object(
               'rows_written', v_written,
               'rows_present', v_existing,
               'cluster_risk_share_sum', v_share_sum,
               'preflight', v_pre,
               'notes', NULLIF(v_note, ''))
     WHERE id = v_log_id;

    RETURN QUERY SELECT v_as_of, p_logic_version, v_written,
                        NULLIF(v_note, '');
END;
$function$;
CREATE OR REPLACE FUNCTION public.atlas_write_segment_verdicts_active(p_as_of date DEFAULT NULL::date, p_logic_version text DEFAULT 'v1:rho0.75:n5:mwr'::text)
 RETURNS TABLE(out_as_of date, out_grouping text, out_rows_written integer, out_notes text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
    v_as_of    date;
    v_written  int;
    v_existing int;
    v_log_id   bigint;
    v_bad      text;
    v_sums     jsonb;
    v_pre      jsonb;
    v_replaced int := 0;
    v_pre_sums jsonb;
    v_failed   text;
    -- MP-5: the ACTIVE account; see atlas_write_verdicts_active.
    v_pid      uuid := public.atlas_active_portfolio();
BEGIN
    v_as_of := COALESCE(p_as_of, CURRENT_DATE);

    INSERT INTO public.sync_log (source, function_name, status, portfolio_id, started_at, details)
    VALUES ('atlas_write_segment_verdicts', 'atlas_write_segment_verdicts', 'running', v_pid, now(),
            jsonb_build_object('as_of', v_as_of, 'logic_version', p_logic_version))
    RETURNING id INTO v_log_id;

    -- Same gate as atlas_write_verdicts, shared rather than reimplemented:
    -- a segment row written against a stale or incoherent book is frozen
    -- into an append-only history that cannot be backfilled.
    SELECT jsonb_agg(jsonb_build_object('check', check_name, 'passed', passed,
                                        'detail', detail)),
           string_agg(check_name || ': ' || detail, '; ') FILTER (WHERE NOT passed)
      INTO v_pre, v_failed
      FROM public.atlas_verdict_preflight();

    IF v_failed IS NOT NULL THEN
        UPDATE public.sync_log
           SET status = 'skipped', finished_at = now(),
               details = details || jsonb_build_object('reason', 'preflight failed',
                                                      'preflight', v_pre)
         WHERE id = v_log_id;
        RETURN QUERY SELECT v_as_of, NULL::text, 0, 'preflight failed: ' || v_failed;
        RETURN;
    END IF;

    PERFORM public.atlas_rematerialise(ARRAY['mv_segment_ex_index']);

    -- Coverage is checked against the SNAPSHOT, before anything is
    -- written. Checking after the insert meant the only way to refuse
    -- was to RAISE, and the RAISE rolled back the sync_log row that
    -- recorded the refusal -- so the 2026-09-07 failure left nothing
    -- in the surface the platform monitors.
    SELECT jsonb_object_agg(g.grouping, jsonb_build_object('segmented', g.n, 'open', ob.n)),
           string_agg(g.grouping || ': ' || g.n || ' segmented vs ' || ob.n || ' open', '; ')
             FILTER (WHERE g.n <> ob.n)
      INTO v_pre_sums, v_bad
      FROM (SELECT grouping, count(*) n FROM public.vw_position_segments GROUP BY grouping) g
      CROSS JOIN (SELECT count(*) n FROM public.mv_position_returns
                   WHERE position_state = 'open') ob;

    IF v_bad IS NOT NULL THEN
        UPDATE public.sync_log
           SET status = 'error', finished_at = now(),
               error_message = 'segmentation does not cover the open book -- ' || v_bad,
               details = details || jsonb_build_object('coverage', v_pre_sums)
         WHERE id = v_log_id;
        RETURN;
    END IF;

    -- REPLACE, not append. Segment ids are derived from the clustering
    -- and are NOT stable across a re-run: 34 appeared and 35 retired
    -- between two writes of the same day. DO NOTHING then adds the new
    -- ids to the stale ones instead of skipping, and the day holds two
    -- segmentations at once.
    DELETE FROM public.segment_verdicts
     WHERE portfolio_id = v_pid AND as_of = v_as_of AND logic_version = p_logic_version;
    GET DIAGNOSTICS v_replaced = ROW_COUNT;

    WITH open_book AS (
        SELECT r.asset_id, r.symbol, r.engine_status, r.net_pnl_usd
          FROM public.mv_position_returns r
         WHERE r.position_state = 'open'
    ),
    -- §2.4b. Weight from vw_risk_analysis; the RISK MEASURE from the Euler
    -- MCTR (defect 3). The old `marginal_vol_contribution * weight` was
    -- weight^2 * vol -- positive by construction, so it could never report a
    -- segment that OFFSETS the book. `risk_contribution_annual` is already
    -- mctr x weight; multiplying again reintroduces exactly that bug.
    risk AS (
        SELECT v.symbol,
               v.weight AS w
          FROM public.vw_risk_analysis v
         WHERE v.symbol IN (SELECT symbol FROM open_book)
    ),
    -- One scan: vw_book_mctr is ~340-450 ms.
    mctr AS (
        SELECT m.symbol,
               m.risk_contribution_annual AS rc,
               m.matrix_as_of
          FROM public.vw_book_mctr m
         WHERE m.symbol IN (SELECT symbol FROM open_book)
    ),
    mx AS (SELECT max(matrix_as_of) AS d FROM mctr),
    -- One basis for every member's excess, on purpose. Members differ in
    -- which counterfactual their CARD is measured against (tier 1 vs tier 2),
    -- and a standard deviation taken across those two bases is not a
    -- dispersion of anything. Tier 2 covers the book, so tier 2 it is, and
    -- `dispersion_basis` says so on every row.
    memb AS (
        SELECT s.grouping, s.segment_id, s.segment_kind, s.segment_label,
               o.symbol, o.net_pnl_usd,
               mc.rc, r.w,
               t2.excess_vs_book_pct AS member_excess,
               bt.thesis_state
          FROM public.vw_position_segments s
          JOIN open_book o ON o.asset_id = s.asset_id
          LEFT JOIN risk r  ON r.symbol = o.symbol
          LEFT JOIN mctr mc ON mc.symbol = o.symbol
          LEFT JOIN public.mv_position_tier2 t2 ON t2.symbol = o.symbol
          LEFT JOIN public.vw_bench_thesis_state bt ON bt.symbol = o.symbol
    ),
    agg AS (
        SELECT m.grouping, m.segment_id,
               min(m.segment_kind)  AS segment_kind,
               min(m.segment_label) AS segment_label,
               count(*)             AS member_count,
               array_agg(m.symbol ORDER BY m.w DESC NULLS LAST) AS members,
               sum(m.rc)            AS rc,
               sum(m.w)             AS w,
               -- A member the matrix cannot price is COUNTED, never
               -- renormalised away.
               count(*) FILTER (WHERE m.rc IS NULL)  AS risk_withheld_n,
               sum(m.w) FILTER (WHERE m.rc IS NULL)  AS risk_withheld_w,
               sum(m.net_pnl_usd)   AS net_pnl_usd,
               stddev_samp(m.member_excess) AS dispersion,
               count(*) FILTER (WHERE m.thesis_state IS NOT NULL)::numeric
                 / NULLIF(count(*), 0)      AS thesis_coverage
          FROM memb m
         GROUP BY m.grouping, m.segment_id
    ),
    ext AS (
        SELECT a.*,
               a.rc / NULLIF(sum(a.rc) OVER (PARTITION BY a.grouping), 0) AS risk_share,
               a.w  / NULLIF(sum(a.w)  OVER (PARTITION BY a.grouping), 0) AS weight_share,
               a.net_pnl_usd
                 / NULLIF(sum(a.net_pnl_usd) OVER (PARTITION BY a.grouping), 0)
                 AS return_contribution_share,
               a.risk_withheld_n AS risk_members_withheld,
               CASE WHEN a.w IS NULL OR a.w = 0 THEN NULL
                    ELSE LEAST(100, GREATEST(0,
                         COALESCE(a.risk_withheld_w, 0) / a.w * 100)) END
                 AS risk_withheld_weight_pct
          FROM agg a
    ),
    best AS (
        SELECT DISTINCT ON (m.grouping, m.segment_id)
               m.grouping, m.segment_id, m.symbol AS sym, m.member_excess AS ex
          FROM memb m WHERE m.member_excess IS NOT NULL
         ORDER BY m.grouping, m.segment_id, m.member_excess DESC
    ),
    worst AS (
        SELECT DISTINCT ON (m.grouping, m.segment_id)
               m.grouping, m.segment_id, m.symbol AS sym, m.member_excess AS ex
          FROM memb m WHERE m.member_excess IS NOT NULL
         ORDER BY m.grouping, m.segment_id, m.member_excess ASC
    ),
    -- Count POSITIONS per label, not labels. jsonb_object_agg keeps the
    -- last value on a duplicate key, so grouping by (symbol, label) --
    -- where every count is 1 -- collapsed a segment to one entry per
    -- distinct label. Group by the key being counted, aggregate once.
    vc AS (
        SELECT g.grouping, g.segment_id, jsonb_object_agg(g.label, g.n) AS counts
          FROM (SELECT p.grouping, p.segment_id,
                       COALESCE(pv.verdict_label, 'unlabelled') AS label,
                       count(*) AS n
                  FROM public.vw_position_segments p
                  JOIN public.position_verdicts pv
                    ON pv.symbol = p.symbol
                   AND pv.portfolio_id = v_pid
                   AND pv.as_of = v_as_of
                   AND pv.logic_version = p_logic_version
                 GROUP BY p.grouping, p.segment_id,
                          COALESCE(pv.verdict_label, 'unlabelled')) g
         GROUP BY g.grouping, g.segment_id
    )
    INSERT INTO public.segment_verdicts (
        portfolio_id, as_of, logic_version, grouping, segment_id, segment_kind, segment_label,
        member_count, members, members_measured, members_withheld, withheld_symbols,
        weight_share, risk_share, return_contribution_share, net_pnl_usd,
        traded_mwr_pct, cf_mwr_pct, excess_vs_book_pct, cf_status, cf_reason,
        dispersion, best_member, best_member_excess_pct,
        worst_member, worst_member_excess_pct, dispersion_basis,
        thesis_coverage, verdict_counts,
        risk_basis, risk_matrix_as_of, risk_members_withheld, risk_withheld_weight_pct)
    SELECT v_pid, v_as_of, p_logic_version, e.grouping, e.segment_id, e.segment_kind, e.segment_label,
           e.member_count, e.members,
           cf.members_measured, cf.members_withheld, COALESCE(cf.withheld_symbols, '{}'),
           e.weight_share, e.risk_share, e.return_contribution_share, e.net_pnl_usd,
           cf.traded_mwr_pct, cf.cf_mwr_pct, cf.excess_vs_book_pct, cf.cf_status, cf.cf_reason,
           CASE WHEN e.member_count >= 2 THEN e.dispersion END,
           b.sym, b.ex, w.sym, w.ex,
           CASE WHEN e.member_count >= 2 AND e.dispersion IS NOT NULL
                THEN 'tier2:excess_vs_book' END,
           e.thesis_coverage,
           vc.counts,
           -- The basis is NULL exactly when the figure is.
           CASE WHEN e.risk_share IS NULL THEN NULL ELSE 'mctr_euler' END,
           CASE WHEN e.risk_share IS NULL THEN NULL ELSE mx.d END,
           e.risk_members_withheld,
           e.risk_withheld_weight_pct
      FROM ext e
      CROSS JOIN mx
      CROSS JOIN LATERAL public.atlas_counterfactual_segment(e.grouping, e.segment_id) cf
      LEFT JOIN best  b  ON b.grouping  = e.grouping AND b.segment_id  = e.segment_id
      LEFT JOIN worst w  ON w.grouping  = e.grouping AND w.segment_id  = e.segment_id
      LEFT JOIN vc       ON vc.grouping = e.grouping AND vc.segment_id = e.segment_id
    ON CONFLICT (portfolio_id, as_of, logic_version, grouping, segment_id) DO NOTHING;

    GET DIAGNOSTICS v_written = ROW_COUNT;

    -- ------------------------------------------------------------------
    -- The cross-row invariant: both shares close to 1.0, within EACH
    -- grouping. This is the §2.4b claim stated as a test.
    -- ------------------------------------------------------------------
    SELECT jsonb_object_agg(g.grouping,
                            jsonb_build_object('risk', round(g.r, 10),
                                               'weight', round(g.w, 10),
                                               'segments', g.n)),
           string_agg(g.grouping || ': risk ' || round(g.r, 6)::text
                                 || ', weight ' || round(g.w, 6)::text, '; ')
             FILTER (WHERE abs(g.r - 1.0) > 0.005 OR abs(g.w - 1.0) > 0.005)
      INTO v_sums, v_bad
      FROM (SELECT grouping, sum(risk_share) AS r, sum(weight_share) AS w, count(*) AS n
              FROM public.segment_verdicts
             WHERE portfolio_id = v_pid AND as_of = v_as_of AND logic_version = p_logic_version
             GROUP BY grouping) g;

    -- Belt and braces. The pre-write check above is the one that can
    -- report; by here the rows are committed-in-transaction, so a RAISE
    -- would take the log with it. Reaching this means the snapshot
    -- closed and the written rows did not, which is a real corruption
    -- and worth losing the log row to refuse.
    IF v_bad IS NOT NULL THEN
        RAISE EXCEPTION 'segment shares closed on the snapshot but not once written -- %', v_bad;
    END IF;

    SELECT count(*) INTO v_existing
      FROM public.segment_verdicts
     WHERE portfolio_id = v_pid AND as_of = v_as_of AND logic_version = p_logic_version;

    IF v_written = 0 AND v_existing = 0 THEN
        UPDATE public.sync_log
           SET status = 'error', finished_at = now(),
               error_message = 'wrote no segment rows and none exist for this as_of'
         WHERE id = v_log_id;
        RAISE EXCEPTION 'segment verdict job produced no rows for % / % and none exist',
                        v_as_of, p_logic_version;
    END IF;

    UPDATE public.sync_log
       SET status = CASE WHEN v_written = 0 THEN 'skipped' ELSE 'success' END,
           finished_at = now(),
           error_message = CASE WHEN v_written = 0
                                THEN 'already written for this as_of' END,
           details = details || jsonb_build_object(
               'rows_written', v_written,
               'rows_present', v_existing,
               'rows_replaced', v_replaced,
               'share_sums', v_sums,
               'preflight', v_pre)
     WHERE id = v_log_id;

    RETURN QUERY
    SELECT v_as_of, sv.grouping, count(*)::int, NULL::text
      FROM public.segment_verdicts sv
     WHERE sv.portfolio_id = v_pid AND sv.as_of = v_as_of AND sv.logic_version = p_logic_version
     GROUP BY sv.grouping;
END;
$function$;

-- ------------------------------------------------------------------------
-- 10. The scheduled entry points run every account
-- ------------------------------------------------------------------------
-- Same signatures and return shapes as before, so cron and any caller are
-- unchanged; one row per account (per grouping for segments), each note
-- prefixed with the account. An account whose run raises is logged against
-- that account and the next one still runs.
create or replace function public.atlas_write_verdicts(p_as_of date default null::date, p_logic_version text default 'v1:rho0.75:n5:mwr'::text, p_refresh boolean default true)
 returns table(out_as_of date, out_logic_version text, out_rows_written integer, out_notes text)
 language plpgsql
 security definer
 set search_path to 'public'
as $fn$
declare
  v_orig text := current_setting('request.headers', true);
  r      record;
  x      record;
begin
  for r in select p.id, p.name from public.portfolios p order by p.is_default desc, p.name loop
    begin
      perform set_config('request.headers',
                         json_build_object('x-atlas-portfolio', r.id::text)::text, true);
      for x in select * from public.atlas_write_verdicts_active(p_as_of, p_logic_version, p_refresh) loop
        out_as_of := x.out_as_of; out_logic_version := x.out_logic_version;
        out_rows_written := x.out_rows_written;
        out_notes := r.name || coalesce(': ' || x.out_notes, '');
        return next;
      end loop;
    exception when others then
      -- The account's own log row rolled back with its subtransaction.
      insert into public.sync_log (source, function_name, status, portfolio_id, started_at,
                                   finished_at, error_message, details)
      values ('atlas_write_verdicts', 'atlas_write_verdicts', 'error', r.id, clock_timestamp(),
              clock_timestamp(), sqlerrm,
              jsonb_build_object('portfolio', r.name, 'as_of', coalesce(p_as_of, current_date),
                                 'logic_version', p_logic_version));
      out_as_of := coalesce(p_as_of, current_date); out_logic_version := p_logic_version;
      out_rows_written := 0; out_notes := r.name || ': error: ' || sqlerrm;
      return next;
    end;
  end loop;
  perform set_config('request.headers', coalesce(v_orig, ''), true);
end
$fn$;

create or replace function public.atlas_write_segment_verdicts(p_as_of date default null::date, p_logic_version text default 'v1:rho0.75:n5:mwr'::text)
 returns table(out_as_of date, out_grouping text, out_rows_written integer, out_notes text)
 language plpgsql
 security definer
 set search_path to 'public'
as $fn$
declare
  v_orig text := current_setting('request.headers', true);
  r      record;
  x      record;
begin
  for r in select p.id, p.name from public.portfolios p order by p.is_default desc, p.name loop
    begin
      perform set_config('request.headers',
                         json_build_object('x-atlas-portfolio', r.id::text)::text, true);
      for x in select * from public.atlas_write_segment_verdicts_active(p_as_of, p_logic_version) loop
        out_as_of := x.out_as_of; out_grouping := x.out_grouping;
        out_rows_written := x.out_rows_written;
        out_notes := r.name || coalesce(': ' || x.out_notes, '');
        return next;
      end loop;
    exception when others then
      insert into public.sync_log (source, function_name, status, portfolio_id, started_at,
                                   finished_at, error_message, details)
      values ('atlas_write_segment_verdicts', 'atlas_write_segment_verdicts', 'error', r.id,
              clock_timestamp(), clock_timestamp(), sqlerrm,
              jsonb_build_object('portfolio', r.name, 'as_of', coalesce(p_as_of, current_date),
                                 'logic_version', p_logic_version));
      out_as_of := coalesce(p_as_of, current_date); out_grouping := null;
      out_rows_written := 0; out_notes := r.name || ': error: ' || sqlerrm;
      return next;
    end;
  end loop;
  perform set_config('request.headers', coalesce(v_orig, ''), true);
end
$fn$;

revoke execute on function public.atlas_write_verdicts_active(date, text, boolean) from public, anon, authenticated;
revoke execute on function public.atlas_write_segment_verdicts_active(date, text) from public, anon, authenticated;
revoke execute on function public.atlas_write_verdicts(date, text, boolean) from public, anon, authenticated;
revoke execute on function public.atlas_write_segment_verdicts(date, text) from public, anon, authenticated;

-- ------------------------------------------------------------------------
-- 11. Assertions
-- ------------------------------------------------------------------------
do $$
begin
  if exists (select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace
              where n.nspname = 'public' and c.relkind = 'm'
                and c.relname in ('mv_book_daily_weights','mv_book_ex_index','mv_position_returns',
                                  'mv_position_tier1','mv_position_tier2','mv_segment_ex_index')) then
    raise exception 'a verdict-chain matview survived the conversion';
  end if;
  if has_table_privilege('anon', 'public.mv_position_returns__acct', 'select')
     or has_table_privilege('anon', 'public.mv_position_returns', 'insert') then
    raise exception 'per-account storage is reachable by anon';
  end if;
  if has_function_privilege('anon', 'public.atlas_write_verdicts(date,text,boolean)', 'execute')
     or has_function_privilege('anon', 'public.atlas_rematerialise(text[])', 'execute') then
    raise exception 'a writer is executable by anon';
  end if;
  if exists (select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace
              where n.nspname = 'public'
                and c.relname in ('vw_position_tier1','vw_position_tier2','vw_position_frozen',
                                  'vw_position_segments','vw_position_cluster_members',
                                  'vw_book_frozen_baseline','vw_default_only_position_returns')
                and pg_get_viewdef(c.oid) ilike '%atlas_on_default_portfolio%') then
    raise exception 'a repointed view still carries a single-book guard';
  end if;
end $$;
