-- reset test rows (no real data yet); cascade clears any outcomes
truncate table decision_outcomes;
truncate table decisions cascade;

-- monotonic sequence for deterministic chain ordering (UUIDs aren't ordered)
alter table decisions add column if not exists seq bigint generated by default as identity;
create index if not exists idx_decisions_seq on decisions(seq);

-- recompute the chain off seq, and stamp distinct times with clock_timestamp()
create or replace function decisions_hash_chain() returns trigger as $$
declare
  last_hash text;
  canon     text;
begin
  new.created_at := clock_timestamp();
  perform pg_advisory_xact_lock(hashtext('atlas_decisions_chain'));
  select content_hash into last_hash from decisions order by seq desc limit 1;
  new.prev_hash := coalesce(last_hash, '');
  canon :=
    coalesce(new.symbol,'')              || '|' ||
    coalesce(new.decided_at::text,'')    || '|' ||
    coalesce(new.decision_type,'')       || '|' ||
    coalesce(new.intent,'')              || '|' ||
    coalesce(new.conviction::text,'')    || '|' ||
    coalesce(new.signal_snapshot::text,'') || '|' ||
    coalesce(new.rationale,'')           || '|' ||
    coalesce(new.prev_hash,'');
  new.content_hash := encode(digest(canon, 'sha256'), 'hex');
  return new;
end $$ language plpgsql;

create or replace view vw_ledger_integrity as
with ordered as (
  select
    id, created_at, content_hash, prev_hash,
    lag(content_hash) over (order by seq) as expected_prev,
    encode(digest(
      coalesce(symbol,'')              || '|' ||
      coalesce(decided_at::text,'')    || '|' ||
      coalesce(decision_type,'')       || '|' ||
      coalesce(intent,'')              || '|' ||
      coalesce(conviction::text,'')    || '|' ||
      coalesce(signal_snapshot::text,'') || '|' ||
      coalesce(rationale,'')           || '|' ||
      coalesce(prev_hash,'')
    , 'sha256'), 'hex') as recomputed_hash
  from decisions
)
select
  count(*)                                                                      as total,
  count(*) filter (where prev_hash is distinct from coalesce(expected_prev,'')) as broken_links,
  count(*) filter (where content_hash is distinct from recomputed_hash)         as tampered_rows,
  (
    count(*) filter (where prev_hash is distinct from coalesce(expected_prev,'')) = 0 and
    count(*) filter (where content_hash is distinct from recomputed_hash) = 0
  )                                                                              as chain_ok,
  max(created_at)                                                               as last_decision_at
from ordered;
