# Generator for supabase/migrations/20260925114040_mp5_per_account_verdict_engine.sql.
# Kept for provenance: it read the LIVE definitions on 2026-09-25 and cannot be
# re-run against a database that has already been converted.
import json, os, re, subprocess, sys
TOK=os.environ['SUPABASE_ACCESS_TOKEN']
def Q(sql):
    out=subprocess.run(['curl','-sS','-X','POST','https://api.supabase.com/v1/projects/vdmojjszvvcithuxwexx/database/query',
        '-H','Authorization: Bearer '+TOK,'-H','Content-Type: application/json','--data',json.dumps({'query':sql})],capture_output=True,text=True).stdout
    r=json.loads(out)
    if isinstance(r,dict): raise SystemExit(r)
    return r
# dependency order: an entry may read only entries before it
MVS=['mv_book_daily_weights','mv_book_ex_index','mv_position_returns','mv_position_tier2','mv_position_tier1','mv_segment_ex_index']
DEPS=['vw_default_only_position_returns','vw_position_cluster_members','vw_position_frozen','vw_position_segments','vw_position_tier1','vw_position_tier2','vw_book_frozen_baseline']
GUARD='WHERE ( SELECT atlas_on_default_portfolio() AS atlas_on_default_portfolio)'
defs={}; cols={}; idx={}
for m in MVS+DEPS:
    defs[m]=Q(f"select pg_get_viewdef('public.{m}'::regclass, true) d")[0]['d']
for m in MVS:
    cols[m]=[r['attname'] for r in Q(f"select attname from pg_attribute where attrelid='public.{m}'::regclass and attnum>0 and not attisdropped order by attnum")]
    idx[m]=[r['indexdef'] for r in Q(f"select indexdef from pg_indexes where schemaname='public' and tablename='{m}' order by indexname")]
def strip_guards(name, d):
    out=d; n=0
    while GUARD in out:
        i=out.index(GUARD)
        pre=out[:i]
        f=pre.rfind('FROM ')
        rel=re.match(r'FROM (\w+)', pre[f:]).group(1)
        assert rel in MVS, (name, rel)
        # drop the guard and the whitespace before it
        j=len(pre.rstrip())
        out=out[:j]+out[i+len(GUARD):]
        n+=1
    return out, n
q=lambda s: '"'+s+'"' if s in ('grouping',) else s
L=[]
L.append("-- generated by gen5b.py from the live definitions; see header in the migration file\n")
L.append("-- 1. retire the matviews (dependents follow the OID until repointed below)")
for m in MVS: L.append(f"alter materialized view public.{m} rename to {m}__retired;")
L.append("\n-- 2. per-account storage, seeded with the rows the matview holds now (the default account's)")
for m in MVS:
    L.append(f"create table public.{m}__acct as\n  select public.atlas_default_portfolio() as portfolio_id, r.* from public.{m}__retired r;")
    L.append(f"alter table public.{m}__acct alter column portfolio_id set not null,\n  add constraint {m}__acct_portfolio_fk foreign key (portfolio_id) references public.portfolios(id) on delete cascade;")
    for d in idx[m]:
        d2=re.sub(r'INDEX (\w+) ON public\.(\w+) USING btree \(', lambda mm: f"INDEX {mm.group(1)}__acct ON public.{m}__acct USING btree (portfolio_id, ", d)
        L.append(d2+';')
    L.append(f"alter table public.{m}__acct enable row level security;")
    L.append(f"revoke all on public.{m}__acct from public, anon, authenticated;")
L.append("\n-- 3. the names every consumer already reads now answer for the active account")
for m in MVS:
    cl=',\n       '.join(q(c) for c in cols[m])
    L.append(f"create view public.{m} as\n select {cl}\n   from public.{m}__acct\n  where portfolio_id = (select public.atlas_active_portfolio());")
    L.append(f"revoke all on public.{m} from public, anon, authenticated;")
    L.append(f"grant select on public.{m} to anon, authenticated, service_role;")
L.append("\n-- 4. the computations the matviews used to hold, as views over the per-account names")
for m in MVS:
    L.append(f"create view public.{m}__compute as\n{defs[m].rstrip().rstrip(';')};")
    L.append(f"revoke all on public.{m}__compute from public, anon, authenticated;")
L.append("\n-- 5. repoint dependents, dropping the single-book guards on these sources")
tot=0
for v in DEPS:
    d,n=strip_guards(v,defs[v]); tot+=n
    L.append(f"-- {v}: {n} guard(s) removed")
    L.append(f"create or replace view public.{v} as\n{d.rstrip().rstrip(';')};")
L.append(f"-- {tot} guards removed in all")
L.append("\n-- 6. drop the retired matviews")
L.append("drop materialized view "+', '.join(f"public.{m}__retired" for m in MVS)+";")
open(sys.argv[1],'w').write('\n'.join(L)+'\n')
json.dump({'cols':cols,'tot':tot},open(sys.argv[1]+'.meta.json','w'))
print('guards removed', tot)
